"""Git Commit: 5cf775f

Revision ID: 0c9bf04c4742
Revises: 3e9844adfede
Create Date: 2026-03-02 12:59:00.487684

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0c9bf04c4742'
down_revision: str | None = '3e9844adfede'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_software_mention', schema=None) as batch_op:
        batch_op.add_column(sa.Column('softcite_mention_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_document_software_mention_mention_context'))
        batch_op.create_index(batch_op.f('ix_document_software_mention_softcite_mention_id'), ['softcite_mention_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_software_mention', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_software_mention_softcite_mention_id'))
        batch_op.create_index(batch_op.f('ix_document_software_mention_mention_context'), ['mention_context'], unique=False)
        batch_op.drop_column('softcite_mention_id')

    # ### end Alembic commands ###
