"""Git Commit: e27fadd.

Revision ID: 1ea1dd59d404
Revises: 5b0e7d54c826
Create Date: 2024-10-15 17:35:53.961614

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ea1dd59d404"
down_revision: str | None = "5b0e7d54c826"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("secondary_doi", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_unique_constraint(None, "document", ["secondary_doi"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "document", type_="unique")
    op.drop_column("document", "secondary_doi")
    # ### end Alembic commands ###
