"""Git Commit: dad3435.

Revision ID: 24be0001da07
Revises: fdad832faf0b
Create Date: 2024-10-16 16:30:43.971190

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24be0001da07"
down_revision: str | None = "fdad832faf0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fwci", sa.Float(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "document_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )
        batch_op.add_column(sa.Column("is_open_access", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_column("is_open_access")
        batch_op.drop_column("document_type")
        batch_op.drop_column("fwci")

    # ### end Alembic commands ###
