"""Git Commit: 039fba6

Revision ID: 3e9844adfede
Revises: 66d00003852c
Create Date: 2026-02-28 09:49:25.311409

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e9844adfede"
down_revision: str | None = "66d00003852c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository_dependency", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ecosystem", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("manifest_paths", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("dependency_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_repository_dependency_dependency_type"),
            ["dependency_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_repository_dependency_ecosystem"), ["ecosystem"], unique=False
        )

    with op.batch_alter_table("repository_import", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("file_paths", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.drop_column("file_path")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository_import", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_path", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("file_paths")

    with op.batch_alter_table("repository_dependency", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repository_dependency_ecosystem"))
        batch_op.drop_index(batch_op.f("ix_repository_dependency_dependency_type"))
        batch_op.drop_column("dependency_type")
        batch_op.drop_column("manifest_paths")
        batch_op.drop_column("ecosystem")

    # ### end Alembic commands ###
