"""Git Commit: eeba738

Revision ID: 43a8e5b6178c
Revises: 6887d527e542
Create Date: 2026-01-09 11:01:22.996390

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '43a8e5b6178c'
down_revision: str | None = '6887d527e542'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_dataset_source')
    with op.batch_alter_table('dataset_source', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_dataset_source_name'), ['name'])

    with op.batch_alter_table('developer_account', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_developer_account_code_host_id'), ['code_host_id', 'username'])

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_doi'), ['doi'])

    with op.batch_alter_table('document_abstract', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_abstract_document_id'), ['document_id'])

    with op.batch_alter_table('document_alternate_doi', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_alternate_doi_doi'), ['doi'])

    with op.batch_alter_table('document_contributor', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_contributor_researcher_id'), ['researcher_id', 'document_id'])

    with op.batch_alter_table('document_contributor_institution', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_contributor_institution_document_contributor_id'), ['document_contributor_id', 'institution_id'])

    with op.batch_alter_table('document_funding_instance', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_funding_instance_document_id'), ['document_id', 'funding_instance_id'])

    with op.batch_alter_table('document_repository_link', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_repository_link_document_id'), ['document_id', 'repository_id'])

    with op.batch_alter_table('document_topic', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_topic_document_id'), ['document_id', 'topic_id'])

    with op.batch_alter_table('funder', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_funder_open_alex_id'), ['open_alex_id'])

    with op.batch_alter_table('funding_instance', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_funding_instance_funder_id'), ['funder_id', 'award_id'])

    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_institution_open_alex_id'), ['open_alex_id'])

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_location_landing_page_url'), ['landing_page_url', 'pdf_url', 'source_id'])

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_repository_code_host_id'), ['code_host_id', 'owner', 'name'])

    with op.batch_alter_table('repository_contributor', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_repository_contributor_repository_id'), ['repository_id', 'developer_account_id'])

    with op.batch_alter_table('repository_file', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_repository_file_repository_id'), ['repository_id', 'path'])

    with op.batch_alter_table('repository_language', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_repository_language_repository_id'), ['repository_id', 'language'])

    with op.batch_alter_table('repository_readme', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_repository_readme_repository_id'), ['repository_id'])

    with op.batch_alter_table('researcher', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_researcher_open_alex_id'), ['open_alex_id'])

    with op.batch_alter_table('researcher_developer_account_link', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_researcher_developer_account_link_researcher_id'), ['researcher_id', 'developer_account_id'])

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_source_open_alex_id'), ['open_alex_id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_topic_open_alex_id'), ['open_alex_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_topic_open_alex_id'), type_='unique')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_source_open_alex_id'), type_='unique')

    with op.batch_alter_table('researcher_developer_account_link', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_researcher_developer_account_link_researcher_id'), type_='unique')

    with op.batch_alter_table('researcher', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_researcher_open_alex_id'), type_='unique')

    with op.batch_alter_table('repository_readme', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_repository_readme_repository_id'), type_='unique')

    with op.batch_alter_table('repository_language', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_repository_language_repository_id'), type_='unique')

    with op.batch_alter_table('repository_file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_repository_file_repository_id'), type_='unique')

    with op.batch_alter_table('repository_contributor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_repository_contributor_repository_id'), type_='unique')

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_repository_code_host_id'), type_='unique')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_location_landing_page_url'), type_='unique')

    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_institution_open_alex_id'), type_='unique')

    with op.batch_alter_table('funding_instance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_funding_instance_funder_id'), type_='unique')

    with op.batch_alter_table('funder', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_funder_open_alex_id'), type_='unique')

    with op.batch_alter_table('document_topic', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_topic_document_id'), type_='unique')

    with op.batch_alter_table('document_repository_link', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_repository_link_document_id'), type_='unique')

    with op.batch_alter_table('document_funding_instance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_funding_instance_document_id'), type_='unique')

    with op.batch_alter_table('document_contributor_institution', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_contributor_institution_document_contributor_id'), type_='unique')

    with op.batch_alter_table('document_contributor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_contributor_researcher_id'), type_='unique')

    with op.batch_alter_table('document_alternate_doi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_alternate_doi_doi'), type_='unique')

    with op.batch_alter_table('document_abstract', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_abstract_document_id'), type_='unique')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_doi'), type_='unique')

    with op.batch_alter_table('developer_account', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_developer_account_code_host_id'), type_='unique')

    with op.batch_alter_table('dataset_source', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_dataset_source_name'), type_='unique')

    op.create_table('_alembic_tmp_dataset_source',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('created_datetime', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_datetime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name=op.f('uq_dataset_source_name'))
    )
    # ### end Alembic commands ###
