"""Git Commit: 93ec439

Revision ID: 66d00003852c
Revises: 2c5b06dbc64a
Create Date: 2026-02-23 17:26:56.715156

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '66d00003852c'
down_revision: str | None = '2c5b06dbc64a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_dependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('software_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('software_name_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_spec', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], name=op.f('fk_repository_dependency_repository_id_repository'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_dependency')),
    sa.UniqueConstraint('repository_id', 'software_name', name=op.f('uq_repository_dependency_repository_id'))
    )
    with op.batch_alter_table('repository_dependency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_dependency_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_dependency_software_name'), ['software_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_dependency_software_name_normalized'), ['software_name_normalized'], unique=False)

    op.create_table('repository_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('software_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('software_name_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], name=op.f('fk_repository_import_repository_id_repository'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_import')),
    sa.UniqueConstraint('repository_id', 'software_name', name=op.f('uq_repository_import_repository_id'))
    )
    with op.batch_alter_table('repository_import', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_import_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_import_software_name'), ['software_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_import_software_name_normalized'), ['software_name_normalized'], unique=False)

    op.create_table('document_software_mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('software_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mention_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('software_name_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_software_mention_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_software_mention')),
    sa.UniqueConstraint('document_id', 'software_name', 'mention_context', name=op.f('uq_document_software_mention_document_id'))
    )
    with op.batch_alter_table('document_software_mention', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_software_mention_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_software_mention_mention_context'), ['mention_context'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_software_mention_software_name'), ['software_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_software_mention_software_name_normalized'), ['software_name_normalized'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_software_mention', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_software_mention_software_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_document_software_mention_software_name'))
        batch_op.drop_index(batch_op.f('ix_document_software_mention_mention_context'))
        batch_op.drop_index(batch_op.f('ix_document_software_mention_document_id'))

    op.drop_table('document_software_mention')
    with op.batch_alter_table('repository_import', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_import_software_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_repository_import_software_name'))
        batch_op.drop_index(batch_op.f('ix_repository_import_repository_id'))

    op.drop_table('repository_import')
    with op.batch_alter_table('repository_dependency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_dependency_software_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_repository_dependency_software_name'))
        batch_op.drop_index(batch_op.f('ix_repository_dependency_repository_id'))

    op.drop_table('repository_dependency')
    # ### end Alembic commands ###
