"""Git Commit: 1b655a9

Revision ID: 6736b5a3b444
Revises: 24be0001da07
Create Date: 2024-10-16 19:03:52.801032

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6736b5a3b444'
down_revision: str | None = '24be0001da07'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('fwci',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('fwci',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
