"""Git Commit: 01195ee.

Revision ID: 6887d527e542
Revises: 92de9f98a387
Create Date: 2025-08-19 10:52:27.449291

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6887d527e542"
down_revision: str | None = "92de9f98a387"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("researcher_developer_account_link", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_snowball_processed_datetime", sa.DateTime(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_researcher_developer_account_link_last_snowball_processed_datetime"),
            ["last_snowball_processed_datetime"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("researcher_developer_account_link", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_researcher_developer_account_link_last_snowball_processed_datetime")
        )
        batch_op.drop_column("last_snowball_processed_datetime")

    # ### end Alembic commands ###
