"""Git Commit: ad127df

Revision ID: 85f44fea018c
Revises: 0c9bf04c4742
Create Date: 2026-03-02 13:03:58.148875

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '85f44fea018c'
down_revision: str | None = '0c9bf04c4742'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_software_mention', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_software_mention_document_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_document_software_mention_document_id'), ['document_id', 'software_name', 'softcite_mention_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_software_mention', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_software_mention_document_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_document_software_mention_document_id'), ['document_id', 'software_name', 'mention_context'])

    # ### end Alembic commands ###
