"""Git Commit: 41f90fc

Revision ID: 963c8b13b478
Revises: 5b0e7d54c826
Create Date: 2024-10-15 17:41:35.352299

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '963c8b13b478'
down_revision: str | None = '5b0e7d54c826'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
