"""Git Commit: cdc1706

Revision ID: 9c54431370e9
Revises: 6887d527e542
Create Date: 2026-01-09 10:47:27.921646

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9c54431370e9'
down_revision: str | None = '6887d527e542'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'code_host', ['code_host_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'location', ['primary_location_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'location', ['best_open_access_location_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_abstract', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_alternate_doi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_contributor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_contributor_institution', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'document_contributor', ['document_contributor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_funding_instance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'funding_instance', ['funding_instance_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_repository_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'dataset_source', ['dataset_source_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('funding_instance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'funder', ['funder_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'source', ['source_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'code_host', ['code_host_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('repository_contributor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'developer_account', ['developer_account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('repository_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('repository_language', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('repository_readme', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('researcher_developer_account_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'developer_account', ['developer_account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researcher_developer_account_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'developer_account', ['developer_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'researcher', ['researcher_id'], ['id'])

    with op.batch_alter_table('repository_readme', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])

    with op.batch_alter_table('repository_language', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])

    with op.batch_alter_table('repository_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])

    with op.batch_alter_table('repository_contributor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'developer_account', ['developer_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'code_host', ['code_host_id'], ['id'])

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'source', ['source_id'], ['id'])

    with op.batch_alter_table('funding_instance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'funder', ['funder_id'], ['id'])

    with op.batch_alter_table('document_topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['id'])

    with op.batch_alter_table('document_repository_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])
        batch_op.create_foreign_key(None, 'dataset_source', ['dataset_source_id'], ['id'])
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])

    with op.batch_alter_table('document_funding_instance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'funding_instance', ['funding_instance_id'], ['id'])
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])

    with op.batch_alter_table('document_contributor_institution', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'document_contributor', ['document_contributor_id'], ['id'])
        batch_op.create_foreign_key(None, 'institution', ['institution_id'], ['id'])

    with op.batch_alter_table('document_contributor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])
        batch_op.create_foreign_key(None, 'researcher', ['researcher_id'], ['id'])

    with op.batch_alter_table('document_alternate_doi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])

    with op.batch_alter_table('document_abstract', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'location', ['best_open_access_location_id'], ['id'])
        batch_op.create_foreign_key(None, 'location', ['primary_location_id'], ['id'])

    with op.batch_alter_table('developer_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'code_host', ['code_host_id'], ['id'])

    # ### end Alembic commands ###
