"""Git Commit: 79a9ba5.

Revision ID: a04dfe729866
Revises: ed27db582ea8
Create Date: 2024-10-22 10:53:39.868806

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a04dfe729866"
down_revision: str | None = "ed27db582ea8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("code_host", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_code_host_name"), ["name"], unique=True)

    with op.batch_alter_table("developer_account", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_developer_account_code_host_id"),
            ["code_host_id"],
            unique=False,
        )

    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_cited_by_count"), ["cited_by_count"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_cited_by_percentile_year_max"),
            ["cited_by_percentile_year_max"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_document_cited_by_percentile_year_min"),
            ["cited_by_percentile_year_min"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_document_document_type"), ["document_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_document_fwci"), ["fwci"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_document_is_open_access"), ["is_open_access"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_open_access_status"),
            ["open_access_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_document_publication_date"),
            ["publication_date"],
            unique=False,
        )

    with op.batch_alter_table("document_abstract", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_abstract_document_id"),
            ["document_id"],
            unique=False,
        )

    with op.batch_alter_table("document_alternate_doi", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_alternate_doi_document_id"),
            ["document_id"],
            unique=False,
        )

    with op.batch_alter_table("document_contributor", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_contributor_document_id"),
            ["document_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_document_contributor_is_corresponding"),
            ["is_corresponding"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_document_contributor_position"), ["position"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_contributor_researcher_id"),
            ["researcher_id"],
            unique=False,
        )

    with op.batch_alter_table(
        "document_contributor_institution", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_contributor_institution_document_contributor_id"),
            ["document_contributor_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_document_contributor_institution_institution_id"),
            ["institution_id"],
            unique=False,
        )

    with op.batch_alter_table("document_funding_instance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_funding_instance_document_id"),
            ["document_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_document_funding_instance_funding_instance_id"),
            ["funding_instance_id"],
            unique=False,
        )

    with op.batch_alter_table("document_repository_link", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_repository_link_dataset_source_id"),
            ["dataset_source_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_document_repository_link_document_id"),
            ["document_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_document_repository_link_repository_id"),
            ["repository_id"],
            unique=False,
        )

    with op.batch_alter_table("document_topic", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_topic_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_topic_score"), ["score"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_topic_topic_id"), ["topic_id"], unique=False
        )

    with op.batch_alter_table("funder", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_funder_name"), ["name"], unique=False)

    with op.batch_alter_table("funding_instance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_funding_instance_award_id"), ["award_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_funding_instance_funder_id"), ["funder_id"], unique=False
        )

    with op.batch_alter_table("institution", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_institution_name"), ["name"], unique=False)

    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_repository_code_host_id"), ["code_host_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_repository_creation_datetime"),
            ["creation_datetime"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_repository_forks_count"), ["forks_count"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_repository_is_fork"), ["is_fork"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_repository_last_pushed_datetime"),
            ["last_pushed_datetime"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_repository_open_issues_count"),
            ["open_issues_count"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_repository_stargazers_count"),
            ["stargazers_count"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_repository_watchers_count"), ["watchers_count"], unique=False
        )

    with op.batch_alter_table("repository_contributor", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_repository_contributor_developer_account_id"),
            ["developer_account_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_repository_contributor_repository_id"),
            ["repository_id"],
            unique=False,
        )

    with op.batch_alter_table("repository_language", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_repository_language_language"), ["language"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_repository_language_repository_id"),
            ["repository_id"],
            unique=False,
        )

    with op.batch_alter_table("repository_readme", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_repository_readme_repository_id"),
            ["repository_id"],
            unique=False,
        )

    with op.batch_alter_table("researcher", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_researcher_cited_by_count"), ["cited_by_count"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_researcher_h_index"), ["h_index"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_researcher_i10_index"), ["i10_index"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_researcher_two_year_mean_citedness"),
            ["two_year_mean_citedness"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_researcher_works_count"), ["works_count"], unique=False
        )

    with op.batch_alter_table(
        "researcher_developer_account_link", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_researcher_developer_account_link_developer_account_id"),
            ["developer_account_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_researcher_developer_account_link_researcher_id"),
            ["researcher_id"],
            unique=False,
        )

    with op.batch_alter_table("topic", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_topic_domain_name"), ["domain_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_topic_field_name"), ["field_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_topic_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_topic_subfield_name"), ["subfield_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topic_subfield_name"))
        batch_op.drop_index(batch_op.f("ix_topic_name"))
        batch_op.drop_index(batch_op.f("ix_topic_field_name"))
        batch_op.drop_index(batch_op.f("ix_topic_domain_name"))

    with op.batch_alter_table(
        "researcher_developer_account_link", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_researcher_developer_account_link_researcher_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_researcher_developer_account_link_developer_account_id")
        )

    with op.batch_alter_table("researcher", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_researcher_works_count"))
        batch_op.drop_index(batch_op.f("ix_researcher_two_year_mean_citedness"))
        batch_op.drop_index(batch_op.f("ix_researcher_i10_index"))
        batch_op.drop_index(batch_op.f("ix_researcher_h_index"))
        batch_op.drop_index(batch_op.f("ix_researcher_cited_by_count"))

    with op.batch_alter_table("repository_readme", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repository_readme_repository_id"))

    with op.batch_alter_table("repository_language", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repository_language_repository_id"))
        batch_op.drop_index(batch_op.f("ix_repository_language_language"))

    with op.batch_alter_table("repository_contributor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repository_contributor_repository_id"))
        batch_op.drop_index(
            batch_op.f("ix_repository_contributor_developer_account_id")
        )

    with op.batch_alter_table("repository", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repository_watchers_count"))
        batch_op.drop_index(batch_op.f("ix_repository_stargazers_count"))
        batch_op.drop_index(batch_op.f("ix_repository_open_issues_count"))
        batch_op.drop_index(batch_op.f("ix_repository_last_pushed_datetime"))
        batch_op.drop_index(batch_op.f("ix_repository_is_fork"))
        batch_op.drop_index(batch_op.f("ix_repository_forks_count"))
        batch_op.drop_index(batch_op.f("ix_repository_creation_datetime"))
        batch_op.drop_index(batch_op.f("ix_repository_code_host_id"))

    with op.batch_alter_table("institution", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_institution_name"))

    with op.batch_alter_table("funding_instance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_funding_instance_funder_id"))
        batch_op.drop_index(batch_op.f("ix_funding_instance_award_id"))

    with op.batch_alter_table("funder", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_funder_name"))

    with op.batch_alter_table("document_topic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_topic_topic_id"))
        batch_op.drop_index(batch_op.f("ix_document_topic_score"))
        batch_op.drop_index(batch_op.f("ix_document_topic_document_id"))

    with op.batch_alter_table("document_repository_link", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_repository_link_repository_id"))
        batch_op.drop_index(batch_op.f("ix_document_repository_link_document_id"))
        batch_op.drop_index(batch_op.f("ix_document_repository_link_dataset_source_id"))

    with op.batch_alter_table("document_funding_instance", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_document_funding_instance_funding_instance_id")
        )
        batch_op.drop_index(batch_op.f("ix_document_funding_instance_document_id"))

    with op.batch_alter_table(
        "document_contributor_institution", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_document_contributor_institution_institution_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_document_contributor_institution_document_contributor_id")
        )

    with op.batch_alter_table("document_contributor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_contributor_researcher_id"))
        batch_op.drop_index(batch_op.f("ix_document_contributor_position"))
        batch_op.drop_index(batch_op.f("ix_document_contributor_is_corresponding"))
        batch_op.drop_index(batch_op.f("ix_document_contributor_document_id"))

    with op.batch_alter_table("document_alternate_doi", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_alternate_doi_document_id"))

    with op.batch_alter_table("document_abstract", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_abstract_document_id"))

    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_publication_date"))
        batch_op.drop_index(batch_op.f("ix_document_open_access_status"))
        batch_op.drop_index(batch_op.f("ix_document_is_open_access"))
        batch_op.drop_index(batch_op.f("ix_document_fwci"))
        batch_op.drop_index(batch_op.f("ix_document_document_type"))
        batch_op.drop_index(batch_op.f("ix_document_cited_by_percentile_year_min"))
        batch_op.drop_index(batch_op.f("ix_document_cited_by_percentile_year_max"))
        batch_op.drop_index(batch_op.f("ix_document_cited_by_count"))

    with op.batch_alter_table("developer_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_developer_account_code_host_id"))

    with op.batch_alter_table("code_host", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_code_host_name"))

    # ### end Alembic commands ###
