"""Git Commit: 1a533c2.

Revision ID: e87d08726abb
Revises: f75d994f9c44
Create Date: 2024-09-16 17:47:25.461548

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e87d08726abb"
down_revision: str | None = "f75d994f9c44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
