"""Git Commit: 9db552b

Revision ID: f7440c2e403d
Revises: 6887d527e542
Create Date: 2026-01-09 10:54:58.221019

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f7440c2e403d'
down_revision: str | None = '6887d527e542'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_source', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_dataset_source_name'), ['name'])

    with op.batch_alter_table('developer_account', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_developer_account_code_host_id'), ['code_host_id', 'username'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_developer_account_code_host_id_code_host'), 'code_host', ['code_host_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_doi'), ['doi'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_document_primary_location_id_location'), 'location', ['primary_location_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_document_best_open_access_location_id_location'), 'location', ['best_open_access_location_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_abstract', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_abstract_document_id'), ['document_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_document_abstract_document_id_document'), 'document', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_alternate_doi', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_alternate_doi_doi'), ['doi'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_document_alternate_doi_document_id_document'), 'document', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_contributor', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_contributor_researcher_id'), ['researcher_id', 'document_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_document_contributor_document_id_document'), 'document', ['document_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_document_contributor_researcher_id_researcher'), 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_contributor_institution', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_contributor_institution_document_contributor_id'), ['document_contributor_id', 'institution_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_document_contributor_institution_institution_id_institution'), 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_document_contributor_institution_document_contributor_id_document_contributor'), 'document_contributor', ['document_contributor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_funding_instance', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_funding_instance_document_id'), ['document_id', 'funding_instance_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_document_funding_instance_funding_instance_id_funding_instance'), 'funding_instance', ['funding_instance_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_document_funding_instance_document_id_document'), 'document', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_repository_link', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_repository_link_document_id'), ['document_id', 'repository_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_document_repository_link_dataset_source_id_dataset_source'), 'dataset_source', ['dataset_source_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_document_repository_link_repository_id_repository'), 'repository', ['repository_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_document_repository_link_document_id_document'), 'document', ['document_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_topic', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_topic_document_id'), ['document_id', 'topic_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_document_topic_document_id_document'), 'document', ['document_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_document_topic_topic_id_topic'), 'topic', ['topic_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('funder', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_funder_open_alex_id'), ['open_alex_id'])

    with op.batch_alter_table('funding_instance', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_funding_instance_funder_id'), ['funder_id', 'award_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_funding_instance_funder_id_funder'), 'funder', ['funder_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_institution_open_alex_id'), ['open_alex_id'])

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_location_landing_page_url'), ['landing_page_url', 'pdf_url', 'source_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_location_source_id_source'), 'source', ['source_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_repository_code_host_id'), ['code_host_id', 'owner', 'name'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_repository_code_host_id_code_host'), 'code_host', ['code_host_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('repository_contributor', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_repository_contributor_repository_id'), ['repository_id', 'developer_account_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_repository_contributor_repository_id_repository'), 'repository', ['repository_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_repository_contributor_developer_account_id_developer_account'), 'developer_account', ['developer_account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('repository_file', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_repository_file_repository_id'), ['repository_id', 'path'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_repository_file_repository_id_repository'), 'repository', ['repository_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('repository_language', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_repository_language_repository_id'), ['repository_id', 'language'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_repository_language_repository_id_repository'), 'repository', ['repository_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('repository_readme', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_repository_readme_repository_id'), ['repository_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_repository_readme_repository_id_repository'), 'repository', ['repository_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('researcher', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_researcher_open_alex_id'), ['open_alex_id'])

    with op.batch_alter_table('researcher_developer_account_link', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_researcher_developer_account_link_researcher_id'), ['researcher_id', 'developer_account_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_researcher_developer_account_link_developer_account_id_developer_account'), 'developer_account', ['developer_account_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_researcher_developer_account_link_researcher_id_researcher'), 'researcher', ['researcher_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_source_open_alex_id'), ['open_alex_id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_topic_open_alex_id'), ['open_alex_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_topic_open_alex_id'), type_='unique')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_source_open_alex_id'), type_='unique')

    with op.batch_alter_table('researcher_developer_account_link', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_researcher_developer_account_link_researcher_id_researcher'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_researcher_developer_account_link_developer_account_id_developer_account'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'developer_account', ['developer_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'researcher', ['researcher_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_researcher_developer_account_link_researcher_id'), type_='unique')

    with op.batch_alter_table('researcher', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_researcher_open_alex_id'), type_='unique')

    with op.batch_alter_table('repository_readme', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_repository_readme_repository_id_repository'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_repository_readme_repository_id'), type_='unique')

    with op.batch_alter_table('repository_language', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_repository_language_repository_id_repository'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_repository_language_repository_id'), type_='unique')

    with op.batch_alter_table('repository_file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_repository_file_repository_id_repository'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_repository_file_repository_id'), type_='unique')

    with op.batch_alter_table('repository_contributor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_repository_contributor_developer_account_id_developer_account'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_repository_contributor_repository_id_repository'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'developer_account', ['developer_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_repository_contributor_repository_id'), type_='unique')

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_repository_code_host_id_code_host'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'code_host', ['code_host_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_repository_code_host_id'), type_='unique')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_location_source_id_source'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'source', ['source_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_location_landing_page_url'), type_='unique')

    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_institution_open_alex_id'), type_='unique')

    with op.batch_alter_table('funding_instance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_funding_instance_funder_id_funder'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'funder', ['funder_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_funding_instance_funder_id'), type_='unique')

    with op.batch_alter_table('funder', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_funder_open_alex_id'), type_='unique')

    with op.batch_alter_table('document_topic', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_topic_topic_id_topic'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_document_topic_document_id_document'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['id'])
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_document_topic_document_id'), type_='unique')

    with op.batch_alter_table('document_repository_link', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_repository_link_document_id_document'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_document_repository_link_repository_id_repository'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_document_repository_link_dataset_source_id_dataset_source'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])
        batch_op.create_foreign_key(None, 'repository', ['repository_id'], ['id'])
        batch_op.create_foreign_key(None, 'dataset_source', ['dataset_source_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_document_repository_link_document_id'), type_='unique')

    with op.batch_alter_table('document_funding_instance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_funding_instance_document_id_document'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_document_funding_instance_funding_instance_id_funding_instance'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])
        batch_op.create_foreign_key(None, 'funding_instance', ['funding_instance_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_document_funding_instance_document_id'), type_='unique')

    with op.batch_alter_table('document_contributor_institution', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_contributor_institution_document_contributor_id_document_contributor'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_document_contributor_institution_institution_id_institution'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'institution', ['institution_id'], ['id'])
        batch_op.create_foreign_key(None, 'document_contributor', ['document_contributor_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_document_contributor_institution_document_contributor_id'), type_='unique')

    with op.batch_alter_table('document_contributor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_contributor_researcher_id_researcher'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_document_contributor_document_id_document'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'researcher', ['researcher_id'], ['id'])
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_document_contributor_researcher_id'), type_='unique')

    with op.batch_alter_table('document_alternate_doi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_alternate_doi_document_id_document'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_document_alternate_doi_doi'), type_='unique')

    with op.batch_alter_table('document_abstract', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_abstract_document_id_document'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_document_abstract_document_id'), type_='unique')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_best_open_access_location_id_location'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_document_primary_location_id_location'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'location', ['best_open_access_location_id'], ['id'])
        batch_op.create_foreign_key(None, 'location', ['primary_location_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_document_doi'), type_='unique')

    with op.batch_alter_table('developer_account', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_developer_account_code_host_id_code_host'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'code_host', ['code_host_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_developer_account_code_host_id'), type_='unique')

    with op.batch_alter_table('dataset_source', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_dataset_source_name'), type_='unique')

    # ### end Alembic commands ###
