"""Git Commit: 29acaf9.

Revision ID: fdad832faf0b
Revises: d959de97d427
Create Date: 2024-10-16 11:37:49.654747

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdad832faf0b"
down_revision: str | None = "d959de97d427"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "open_access_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_column("open_access_status")

    # ### end Alembic commands ###
