project:
  type: website
  output-dir: _build
  render:
    - "qss-code-authors.qmd"
    - "supplementary-material.qmd"
    - "!extra-notebooks/"
    - "!extra-data/"
    - "!arxiv-qss-code-authors.tex"
