---
title: "Code Contribution and Credit in Science"
authors:
  - name: "Eva Maxfield Brown (0000-0003-2564-0373)"
    email: evamxb@uw.edu
    orcid: 0000-0003-2564-0373
    affiliations:
      - ref: 1
    attributes:
        corresponding: true
  - name: "Isaac Slaughter (0000-0002-1911-2374)"
    orcid: 0000-0002-1911-2374
    affiliations:
      - ref: 1
  - name: "Nicholas Weber (0000-0002-6008-3763)"
    orcid: 0000-0002-6008-3763
    affiliations:
      - ref: 1

affiliations:
  - id: 1
    name: University of Washington Information School

abstract: |
    Software development has become essential to scientific research, but its relationship to traditional metrics of scholarly credit remains poorly understood. We develop a dataset of approximately 140,000 paired research articles and code repositories, and a predictive model that matches research article authors with software repository developer accounts. We use this dataset to investigate how software development activities influence credit allocation in collaborative scientific settings. Our findings reveal significant patterns distinguishing software contributions from traditional authorship credit. We find that \~30% of articles include non-author code contributors—individuals who participated in software development but received no authorship recognition. While code-contributing authors provide a \~4.2% increase in article citations, this effect becomes non-significant when controlling for domain, article type, and open access status. First authors are significantly more likely to be code contributors than other author positions. Notably, we identify a negative relationship between coding frequency and scholarly impact metrics. Authors who contribute code more frequently exhibit progressively lower h-indices than non-coding colleagues, even when controlling for publication count, author position, domain, and article type. These results suggest a disconnect between software contributions and credit, highlighting important implications for institutional reward structures and science policy.

keywords:
    - scientific software
    - research software
    - authorship
    - contributorship
    - credit

## Basics
bibliography: main.bib

## Number sections (required for section cross ref)
number-sections: true

## Citation Style Language
# See https://github.com/citation-style-language/styles for more options
# Use APA style for citations and reference formatting.
csl: apa.csl

## Specific for target format
format:
#   html:
#    standalone: true
#    embed-resources: true
#    toc: true
#    toc-location: left
#    reference-location: margin
#    citation-location: document
#    execute:
#      echo: false
#      warning: false

  elsevier-pdf:
    keep-tex: true
    cite-method: citeproc
    toc: false
    execute:
      echo: false
      warning: false

    include-in-header:  
      - text: |
          \usepackage{booktabs}    % For professional-looking tables
          \usepackage{multirow}    % For merged cells
          \usepackage{siunitx}     % For number alignment
          \usepackage[table]{xcolor}  % The 'table' option is crucial for \rowcolors to work
          \usepackage{float}
          \floatplacement{table}{H}
        
    journal:
      cite-style: number
      name: "in-progress"
      model: "3p"
      layout: "onecolumn"

    # # Word count
    # citeproc: false
    # filters:
    #   - at: pre-quarto
    #     path: _extensions/andrewheiss/wordcount/citeproc.lua
    #   - at: pre-quarto
    #     path: _extensions/andrewheiss/wordcount/wordcount.lua
---

# Introduction

```{python}
#| output: false

from collections import OrderedDict
from datetime import datetime
from io import StringIO
import yaml
import os
from pathlib import Path
import shutil

import colormaps as cmaps
import IPython.display
import matplotlib.pyplot as plt
import numpy as np
import opinionated  # noqa
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
from sci_soft_models.dev_author_em import data as sci_soft_models_data
from scipy.stats import (
    binomtest,
    chi2_contingency,
    pearsonr,
)
from statsmodels.stats.multitest import multipletests
from sqlalchemy import text, create_engine

from rs_graph.db import models as db_models
from rs_graph.db.constants import PROD_DATABASE_FILEPATH

# Get db engine for production database
db_conn = create_engine(f"sqlite:///{PROD_DATABASE_FILEPATH}")

# Set seaborn style
plt.style.use("opinionated_rc")
sns.set_palette(
    cmaps.bold[2:]._colors.tolist(),
)

# Get or set USE_SAMPLE
if "QSS_CODE_AUTHORSHIP_USE_SAMPLE" in os.environ:
    USE_SAMPLE = bool(int(os.environ["QSS_CODE_AUTHORSHIP_USE_SAMPLE"]))
else:
    USE_SAMPLE = True
USE_SAMPLE = False

# Other paths
EXTRA_DATA_PATH = Path.cwd() / "extra-data"
```

```{python}
def read_table(table: str) -> pd.DataFrame:
    return pd.read_sql(text(f"SELECT * FROM {table}"), db_conn)


# Read all data from database
doc_repo_links = read_table(db_models.DocumentRepositoryLink.__tablename__)
researchers = read_table(db_models.Researcher.__tablename__)
devs = read_table(db_models.DeveloperAccount.__tablename__)
documents = read_table(db_models.Document.__tablename__)
document_contributors = read_table(db_models.DocumentContributor.__tablename__)
repositories = read_table(db_models.Repository.__tablename__)
repository_contributors = read_table(db_models.RepositoryContributor.__tablename__)
topics = read_table(db_models.Topic.__tablename__)
document_topics = read_table(db_models.DocumentTopic.__tablename__)
dataset_sources = read_table(db_models.DatasetSource.__tablename__)
researcher_dev_links = read_table(
    db_models.ResearcherDeveloperAccountLink.__tablename__
)
document_alternate_dois = read_table(
    db_models.DocumentAlternateDOI.__tablename__
)
repository_programming_languages = read_table(
    db_models.RepositoryLanguage.__tablename__
)

# Drop all "updated_datetime" and "created_datetime" columns
for df in [
    doc_repo_links,
    researchers,
    devs,
    documents,
    document_contributors,
    repositories,
    repository_contributors,
    topics,
    document_topics,
    dataset_sources,
    researcher_dev_links,
    repository_programming_languages,
]:
    df.drop(columns=["updated_datetime", "created_datetime"], inplace=True)


# Get stats for many-to-many now before all the drops
many_to_many_doc_repo_links = len(doc_repo_links)
many_to_many_unique_docs = len(documents)
many_to_many_unique_repos = len(repositories)
many_to_many_descriptive_statistics_for_docs = doc_repo_links.groupby(
    "document_id"
).size().describe(percentiles=[0.95, 0.97, 0.99])
many_to_many_descriptive_statistics_for_repos = doc_repo_links.groupby(
    "repository_id"
).size().describe(percentiles=[0.95, 0.97, 0.99])

# Get stats per data source
many_to_many_doc_repo_links_per_source = {}
many_to_many_unique_docs_per_source = {}
many_to_many_unique_repos_per_source = {}
for _, data_source in dataset_sources.iterrows():
    # Get total article-repo pairs
    source_doc_repo_links = doc_repo_links[
        doc_repo_links["dataset_source_id"] == data_source["id"]
    ]
    many_to_many_doc_repo_links_per_source[data_source["name"]] = len(source_doc_repo_links)
    many_to_many_unique_docs_per_source[data_source["name"]] = len(
        documents[documents["id"].isin(source_doc_repo_links["document_id"])]
    )
    many_to_many_unique_repos_per_source[data_source["name"]] = len(
        repositories[repositories["id"].isin(source_doc_repo_links["repository_id"])]
    )

# Make all print-ready
for data_source_name, count in many_to_many_doc_repo_links_per_source.items():
    many_to_many_doc_repo_links_per_source[data_source_name] = "{:,}".format(count)
for data_source_name, count in many_to_many_unique_docs_per_source.items():
    many_to_many_unique_docs_per_source[data_source_name] = "{:,}".format(count)
for data_source_name, count in many_to_many_unique_repos_per_source.items():
    many_to_many_unique_repos_per_source[data_source_name] = "{:,}".format(count)

print_ready_m2m_doc_repo_links_count = "{:,}".format(many_to_many_doc_repo_links)
print_ready_m2m_unique_docs_count = "{:,}".format(many_to_many_unique_docs)
print_ready_m2m_unique_repos_count = "{:,}".format(many_to_many_unique_repos)
print_ready_m2m_median_docs = "{:,}".format(
    int(many_to_many_descriptive_statistics_for_docs["50%"])
)
print_ready_m2m_95th_percentile_docs = "{:,}".format(
    int(many_to_many_descriptive_statistics_for_docs["95%"])
)
print_ready_m2m_97th_percentile_docs = "{:,}".format(
    int(many_to_many_descriptive_statistics_for_docs["97%"])
)
print_ready_m2m_99th_percentile_docs = "{:,}".format(
    int(many_to_many_descriptive_statistics_for_docs["99%"])
)
print_ready_m2m_median_repos = "{:,}".format(
    int(many_to_many_descriptive_statistics_for_repos["50%"])
)
print_ready_m2m_95th_percentile_repos = "{:,}".format(
    int(many_to_many_descriptive_statistics_for_repos["95%"])
)
print_ready_m2m_97th_percentile_repos = "{:,}".format(
    int(many_to_many_descriptive_statistics_for_repos["97%"])
)
print_ready_m2m_99th_percentile_repos = "{:,}".format(
    int(many_to_many_descriptive_statistics_for_repos["99%"])
)

# Read in the programming languages file
# File acquired from:
# https://github.com/github-linguist/linguist/blob/1d913bbdff8e31f1dcf0ba6ce482f4edb5715fc7/lib/linguist/languages.yml
with open(EXTRA_DATA_PATH / "programming-languages.yml", "r") as open_file:
    programming_language_data = yaml.safe_load(open_file)

# Get just the programming languages (exclude data and other file types)
programming_language_names = [
    name
    for name, data
    in programming_language_data.items()
    if data["type"] == "programming"
]

# Filter down the rows in repository_programming_languages to only include
# repos that have code
repository_programming_languages = repository_programming_languages[
    repository_programming_languages["language"].isin(programming_language_names)
]

# Get the set of repository ids that have programming files
repositories_with_code = repository_programming_languages["repository_id"].unique()

# Specifically drop doc_repo_links "id" column
# It isn't used and will get in the way later when we do a lot of joins
doc_repo_links.drop(columns=["id"], inplace=True)

# Construct reduced doc_repo_links
original_doc_repo_links_len = len(doc_repo_links)
doc_repo_links = doc_repo_links.drop_duplicates(subset=["document_id"], keep=False)
doc_repo_links = doc_repo_links.drop_duplicates(subset=["repository_id"], keep=False)

one_to_one_doc_repo_links_len = len(doc_repo_links)
m2m_to_1to1_doc_repo_links_dropped = (
    many_to_many_doc_repo_links - one_to_one_doc_repo_links_len
)
print_ready_m2m_to_1to1_doc_repo_links_dropped = "{:,}".format(m2m_to_1to1_doc_repo_links_dropped)

# Reduce other tables to only documents / repositories in the updated doc_repo_links
documents = documents[documents["id"].isin(doc_repo_links["document_id"])]
repositories = repositories[repositories["id"].isin(doc_repo_links["repository_id"])]
document_contributors = document_contributors[
    document_contributors["document_id"].isin(documents["id"])
]
repository_contributors = repository_contributors[
    repository_contributors["repository_id"].isin(repositories["id"])
]
document_topics = document_topics[document_topics["document_id"].isin(documents["id"])]

# Reduce researchers and devs to only those in the
# updated document_contributors and repository_contributors
researchers = researchers[
    researchers["id"].isin(document_contributors["researcher_id"])
]
devs = devs[devs["id"].isin(repository_contributors["developer_account_id"])]
researcher_dev_links = researcher_dev_links[
    (
        researcher_dev_links["researcher_id"].isin(researchers["id"])
        & researcher_dev_links["developer_account_id"].isin(devs["id"])
    )
]

# Sort document topics and keep first
document_topics = document_topics.sort_values("score", ascending=False)
document_topics = document_topics.drop_duplicates(subset=["document_id"], keep="first")

# Create document, document topic merged table
merged_document_topics = pd.merge(
    document_topics, topics, left_on="topic_id", right_on="id"
)

# Create basic merged tables
merged_document_contributor_doc_repo_links = pd.merge(
    document_contributors, doc_repo_links, left_on="document_id", right_on="document_id"
)
merged_repository_contributor_doc_repo_links = pd.merge(
    repository_contributors,
    doc_repo_links,
    left_on="repository_id",
    right_on="repository_id",
)

# Compute stats for data sources
data_source_stats = []
article_repo_pairs_per_source = {}
for _, data_source in dataset_sources.iterrows():
    # Get total article-repo pairs
    data_source_stats.append(
        {
            "data_source": data_source["name"],
            "n_article_repo_pairs": len(
                doc_repo_links[doc_repo_links["dataset_source_id"] == data_source["id"]]
            ),
            "n_authors": merged_document_contributor_doc_repo_links.loc[
                merged_document_contributor_doc_repo_links["dataset_source_id"]
                == data_source["id"]
            ]["researcher_id"].nunique(),
            "n_devs": merged_repository_contributor_doc_repo_links.loc[
                merged_repository_contributor_doc_repo_links["dataset_source_id"]
                == data_source["id"]
            ]["developer_account_id"].nunique(),
        }
    )

    # Store article-repo pairs per source for later use
    article_repo_pairs_per_source[data_source["name"]] = len(
        doc_repo_links[doc_repo_links["dataset_source_id"] == data_source["id"]]
    )

# Make the article_repo_pairs_per_source print-ready
for data_source_name, count in article_repo_pairs_per_source.items():
    article_repo_pairs_per_source[data_source_name] = "{:,}".format(count)

# Create topic merged tables
merged_doc_repo_links_topics = pd.merge(
    doc_repo_links, document_topics, left_on="document_id", right_on="document_id"
).merge(topics, left_on="topic_id", right_on="id")
merged_doc_repo_links_topics_document_contributors = pd.merge(
    merged_doc_repo_links_topics,
    document_contributors,
    left_on="document_id",
    right_on="document_id",
)
merged_doc_repo_links_topics_repository_contributors = pd.merge(
    merged_doc_repo_links_topics,
    repository_contributors,
    left_on="repository_id",
    right_on="repository_id",
)

# Compute stats for domains
domain_stats = []
for domain in merged_doc_repo_links_topics.domain_name.unique():
    # Get total article-repo pairs
    domain_stats.append(
        {
            "domain": domain,
            "n_article_repo_pairs": len(
                merged_doc_repo_links_topics[
                    merged_doc_repo_links_topics["domain_name"] == domain
                ]
            ),
            "n_authors": merged_doc_repo_links_topics_document_contributors.loc[
                merged_doc_repo_links_topics_document_contributors["domain_name"]
                == domain
            ]["researcher_id"].nunique(),
            "n_devs": merged_doc_repo_links_topics_repository_contributors.loc[
                merged_doc_repo_links_topics_repository_contributors["domain_name"]
                == domain
            ]["developer_account_id"].nunique(),
        }
    )

# Create document merged tables
merged_doc_repo_links_documents = pd.merge(
    doc_repo_links, documents, left_on="document_id", right_on="id"
)
merged_doc_repo_links_documents_document_contributors = pd.merge(
    merged_doc_repo_links_documents,
    document_contributors,
    left_on="document_id",
    right_on="document_id",
)
merged_doc_repo_links_documents_repository_contributors = pd.merge(
    merged_doc_repo_links_documents,
    repository_contributors,
    left_on="repository_id",
    right_on="repository_id",
)

# Compute stats for document types
# This isn't a standard data pull
# In short:
# - pairs from PLOS are "research articles"
# - pairs from JOSS are "software articles"
# - pairs from SoftwareX are "software articles"
# - pairs from Papers with Code / ArXiv are "pre-prints"
#   UNLESS they have been published in a journal
# All of those should be easy to assert / apply a label to with the exception
# of Papers with Code / ArXiv pre-prints that have been published in a journal
# In that case, we need to look at the existing document type in the database
# If the document type is "preprint" use preprint, otherwise, if it's anything else,
# use "research article"

# Create a "reduced_doc_types" dataframe with document_id and "reduced_doc_type"
# columns
reduced_doc_types_rows = []
# We can use the "reduced_doc_types" dataframe to calculate the stats

# Iter over data sources even though we are looking for doc types
for _, data_source in dataset_sources.iterrows():
    # Get total article-repo pairs
    doc_type = None
    if data_source["name"] in ["plos", "joss", "softwarex"]:
        if data_source["name"] == "plos":
            doc_type = "research article"
        else:
            doc_type = "software article"

        # Add all document_ids to reduced_doc_types_rows
        reduced_doc_types_rows.extend(
            [
                {"document_id": doc_id, "reduced_doc_type": doc_type}
                for doc_id in doc_repo_links[
                    (doc_repo_links["dataset_source_id"] == data_source["id"])
                ]["document_id"]
            ]
        )

    # Handle PwC
    else:
        # Get preprint pairs
        preprint_pairs = merged_doc_repo_links_documents[
            (merged_doc_repo_links_documents["dataset_source_id"] == data_source["id"])
            & (merged_doc_repo_links_documents["document_type"] == "preprint")
        ]

        # Add all document_ids to reduced_doc_types_rows
        reduced_doc_types_rows.extend(
            [
                {"document_id": doc_id, "reduced_doc_type": "preprint"}
                for doc_id in preprint_pairs["document_id"]
            ]
        )

        # Get research article pairs
        # This is the same just inverted to != "preprint"
        research_article_pairs = merged_doc_repo_links_documents[
            (merged_doc_repo_links_documents["dataset_source_id"] == data_source["id"])
            & (merged_doc_repo_links_documents["document_type"] != "preprint")
        ]

        # Add all document_ids to reduced_doc_types_rows
        reduced_doc_types_rows.extend(
            [
                {"document_id": doc_id, "reduced_doc_type": "research article"}
                for doc_id in research_article_pairs["document_id"]
            ]
        )

# Create reduced_doc_types dataframe
reduced_doc_types = pd.DataFrame(reduced_doc_types_rows)
```

```{python}
# Precompute DOI resolution statistics as that will be referenced
# in the Data and Methods section

# Groupby "name" and get percent have resolved dois
per_dataset_doi_resolution = {}
per_dataset_doi_resolved_counts = {}
for dataset_source, group in doc_repo_links.merge(
    dataset_sources,
    left_on="dataset_source_id",
    right_on="id",
).groupby("name"):
    # Get unique articles in this group
    unique_group_articles = group.drop_duplicates(subset=["document_id"])

    # Get the number of articles from this dataset
    n_articles_in_group = len(unique_group_articles)
    
    # Get the number of articles with an alternate doi in this group
    # Where the alternate doi isn't the same as the document doi
    group_document_alternate_dois = document_alternate_dois[
        (document_alternate_dois["document_id"].isin(unique_group_articles["document_id"]))
        & (~document_alternate_dois["doi"].str.lower().isin(documents["doi"].str.lower()))
    ]
    n_articles_with_alt_doi = len(group_document_alternate_dois)

    # Add to results
    per_dataset_doi_resolved_counts[dataset_source] = n_articles_with_alt_doi
    per_dataset_doi_resolution[dataset_source] = n_articles_with_alt_doi / n_articles_in_group

# Get overall doi resolution
n_articles = len(documents)

# Get the number of articles with an alternate doi
# Where the alternate doi isn't the same as the document doi
unique_document_alternate_dois = document_alternate_dois[
    ~document_alternate_dois["doi"].str.lower().isin(documents["doi"].str.lower())
]
n_articles_with_alt_doi = len(unique_document_alternate_dois)

# Compute overall doi resolution
overall_doi_resolution = n_articles_with_alt_doi / n_articles

print_ready_plos_doi_resolved = "{:,}".format(per_dataset_doi_resolved_counts["plos"])
print_ready_joss_doi_resolved = "{:,}".format(per_dataset_doi_resolved_counts["joss"])
print_ready_softwarex_doi_resolved = "{:,}".format(per_dataset_doi_resolved_counts["softwarex"])
print_ready_pwc_doi_resolved = "{:,}".format(per_dataset_doi_resolved_counts["pwc"])
```

Recent advances in genomic sequencing, climate modeling, particle physics, and neuroimaging have all required the development of novel scientific software [@hocquet2024software]. In many ways, software development has changed how scientific work is organized and performed, but we lack large-scale quantitative evidence characterizing these effects. This lack of evidence has important consequences. Scientific institutions continue to rely heavily on bibliometric indicators to evaluate research productivity [@haustein2014use], but software is rarely mentioned or cited in research publications [@du2021softcite]. As a result, researchers who invest substantial effort in building computational tools may face systematic disadvantages in career advancement. We argue that understanding whether and how software contributions translate into formal scientific credit is important for designing equitable reward structures and evidence-based science policy.

The challenge of measuring software's role in science stems, in part, from the historical separation of code from publication. Scientific articles and their metadata (e.g. author lists, citations, and acknowledgments) can provide a valuable tool for estimating productivity, tracing collaboration, or inferring impact [@fortunato2018science]. However, software contributions often remain invisible in these records, making it difficult to quantify their relationship to traditional markers of scientific productivity [@weber2014paratexts]. As a result, studies regarding the maintainers and contributors of scientific software have relied primarily on self-reports (surveys) [@Carver2022ASO] or participant observation (ethnographies) [@paine2017has], which provide valuable insights but are limited in the scope and generalizability. 

In the following paper, we overcome this challenge by constructing a dataset (`rs-graph-v1`) of 138,596 research articles and their associated code repositories. Using this data we then develop a machine learning model to match article authors with repository contributor accounts. By connecting papers to repositories, and authors to developers, we are able to observe both the presence and effect of code contributions across different authorship positions and examine how coding activity relates to both article-level citations and career-level productivity metrics (e.g., h-index). This approach enables us to address fundamental questions about the scientific reward system: How do software contributions correspond to authorship positions? Does coding effort translate into citation impact? How do patterns of code contribution relate to long-term career trajectories?

In analyzing a filtered subset of the `rs-graph-v1` dataset, we identify three patterns that distinguish code contributions from other forms of scientific recognition. First, we show that 28.6% (n=5,694) of articles have non-author code-contributors, or individuals who may have helped create the software but received no formal authorship credit. We also show that code-contributing authors are associated with a modest increase in article-level impact metrics (on average, a 4.2% increase in citations per code-contributing author), but these effects become statistically non-significant when controlling for domain, article type, and open access status. Second, we find that first authors are significantly more likely to be code contributors than other author positions across all conditions tested. Third, we find a negative relationship between coding frequency and scholarly impact: Authors who contribute code more frequently show progressively lower h-indices than their non-coding peers, a pattern that persists even when controlling for publication count, and author's most common author position (first, middle, or last), domain (Physical Sciences, Health Sciences, Life Sciences, or Social Sciences), and article type (preprint, research article, or software article)[^1].

[^1]: We use the phrase "most common" to mean most frequent, and in the case of a tie, their most recent. That is, if an author has been first author on four publications in our dataset, middle author on two publications, and has never been last author, they are considered a "first author" for the purposes of our analysis. We discuss the limitations of this approach in the @sec-discussion.

The remainder of this paper proceeds as follows: First, we review related work regarding software development and the recognition of code contributors in scientific credit systems. In doing so, we motivate three specific hypotheses that guide our investigation. Next, we provide an overview of our data and methods, describing how we linked articles to repositories, trained and evaluated a predictive model for entity matching, and applied this model across each article-repository pair. We then present our analysis, focusing on article-level dynamics before moving to individual-level (career) patterns, formally accepting or rejecting each hypothesis based on our findings.

# Background {#sec-background}

The proper allocation of credit has been a longstanding topic in social studies of science. Merton's description of a "Matthew Effect" is perhaps the most famous account of a cumulative advantage in publishing, where established scientists receive more attention for work of similar importance or value than their less established peers [@merton1968matthew]. Contemporary studies of science continue to demonstrate important aspects of the dilemma. Dashun Wang et al. show that random career outcomes and the "hot streak" phenomenon suggest that cumulative advantage and early career success may be less predictive of long-term impact than traditionally assumed, complicating how we understand the accrual of scientific credit over time [@wang2013quantifying; @liu2018hot]. Separately, work on team science demonstrates that larger teams receive disproportionate credit compared to smaller teams producing equally impactful work, further illustrating how credit allocation deviates from underlying contributions [@wu2019large].

In quantitative work, the attribution of credit is most often established using proxies in bibliographic data like author order [@zuckerman1968patterns; @sarsons2017recognition; @sauermann2017authorship], which is an imperfect means of assigning credit, and doing so may exacerbate existing inequalities [@west2013role]. More recent work developing algorithms to assign credit [@shen2014collective] and formally document contributor roles [@allen2014publishing] are aimed at trying to improve upon author order as the status quo mechanism for assigning credit in collaborative settings. Further, the use of contributor statements as data have provided important insights into the actual division of labor in scientific collaborations and revealed systematic patterns in how different types of contributions are valued and recognized across fields [@lu2020co; @lu2022contributorship].

Among the contributions systematically undervalued in collaborative science are technical and infrastructural contributions, particularly software development. While contributor role taxonomies have begun to make visible the diverse forms of labor that constitute scientific work, these systems still struggle to adequately recognize the significance of technical contributions that enable research, but may not fit traditional notions of intellectual authorship [@Larivire2020InvestigatingTD]. Even less is known about the broader patterns of attention that software-producing research teams receive, and under what conditions technical contributions achieve visibility in an attention economy driven by citations. We argue that understanding these patterns requires examining how team composition and software contributions relate to scientific attention at scale.

Next, we build upon these general findings to motivate three specific hypotheses about code contributions and credit that we then test using the `rs-graph-v1` dataset.

## H1: Research Team Composition and Scientific Attention

In collaborative settings, experimental and theoretical research often receives more citations than methods-focused contributions, with the exception being when methods represent foundational shifts in a field [@Aksnes2006CitationRA; @LIU2023101432; @Chen2024ExploringSC]. Software is often positioned as a methodological contribution and, as a result, can be found in some of the highest-cited papers of the 21st century [@jin2015significance; @hampton2013big; @researchsoftwareclassifications].

Prior work also establishes a positive relationship between team size and citation count, where larger and more diverse teams produce higher-impact scientific work [@Franceschet2010TheEO; @Larivire2014TeamSM; @yoo2024interaction]. Research in empirical software studies similarly finds that larger development teams tend to create more reliable software with fewer defects [@Wyss2023NothingBut, @herbsleb2003empirical], though this comes at the expense of slower development cycles. These findings suggest that team size may be particularly important in scientific software development, where technical robustness and reproducibility remain gold standards [@milewicz2018talk].

We argue that the unique characteristics of scientific software development — including implementing novel algorithms, requiring deep domain knowledge, and an increased emphasis on reproducibility [@muna2016astropyproblem; @Howison2013IncentivesAI] — make team composition especially important for understanding credit allocation. Software development in organized teams may enhance scientific impact through multiple mechanisms: teams can produce more robust and generalizable software tools for methodological contributions while enabling more sophisticated computational analyses and larger-scale data processing for experimental work.

Given these patterns in team dynamics, software development practices, and citations in collaborative research, we propose that:

*H1: The number of individuals contributing code to a publication's associated repository positively correlates with the article's citation count.*

## H2: Author Roles and Technical Contributions

Author positions in scientific publications signal specific roles and responsibilities [@shen2014collective], a relationship that can be contemporarily studied through contribution role taxonomies like CRediT [@lariviere2016contributorship]. In this literature, analyses of contribution patterns consistently show that software development, data analysis, and visualization tasks typically fall to first authors [@lariviere2016contributorship; @Jnior2016PatternsOA; @Larivire2020InvestigatingTD; @sauermann2017authorship]. While these contribution patterns are often inferred from self-reported roles (e.g., CRediT) or disciplinary conventions, the linking of publications to version-controlled software repositories provides a novel window into the actual coding contributions associated with scientific papers. Given the established tendency for first authors to undertake primary research execution, including technical development, we anticipate that this pattern will be directly observable via the commit histories of scientific software repositories. Given prior findings about the distribution of technical responsibilities within research teams, we expect these repository records to reflect similar patterns of engagement with software development:

*H2a: First authors have higher code contribution rates than authors in other positions.*

Furthermore, studies that use contribution taxonomies like CRediT reveal that first authors and corresponding authors, while occasionally the same individual, often take on distinct responsibilities [@birnbaum2023should]. Corresponding authors traditionally bear responsibility for the integrity, archiving, and long-term availability of research artifacts and underlying data [@teunis2015corresponding; @sauermann2017authorship; @da2013corresponding; @BHANDARI20141049]. As software becomes an increasingly critical, complex, and integral research artifact in many disciplines, it logically follows that stewardship of these software components should align with the responsibilities of being a corresponding author. Given prior findings about the distribution of responsibilities within research teams and the expectation of stewardship of created artifacts, we expect repository records to reflect similar patterns of engagement with software development:

*H2b: Corresponding authors have higher code contribution rates than non-corresponding authors.*

## H3: Code Contribution and Individual Scientific Impact

Despite the increasingly central role of software in science, researchers who dedicate significant effort to its development often face systemic hurdles in receiving formal scientific credit. Their contributions may be relegated to acknowledgment sections rather than rewarded with authorship credit [@weber2014paratexts]. Further, the scholarly practice of software citation remains inconsistent, frequently undervaluing crucial maintenance and extension work [@Carver2022ASO; @olivier_philippe_2019_2585783; @Lamprecht2020TowardsFP; @Katz2020RecognizingTV; @Smith2016SoftwareCP]. The h-index, a widely used proxy for an individual's cumulative scientific impact, is derived from an individual's record of formally authored publications and the citations these publications receive [@hirsch2005index]. Consequently, if substantial time and intellectual effort are invested in software development that does not consistently translate into formal authorship on associated research papers, or if the software outputs themselves are not robustly and formally cited in a way that accrues to the individual developer, then the primary activities that build a researcher's h-index are effectively diminished or bypassed.

This creates a structural misalignment where contributions essential for scientific advancement (i.e., software development and maintenance) may not adequately capture and could even detract from time spent on activities that bolster traditional bibliometric indicators of individual success. While collaborative software development may yield short-term benefits through increased citations on individual papers (as suggested by H1), researchers specializing in code development may face long-term career disadvantages as their expertise becomes increasingly divorced from traditional publication pathways that drive academic recognition and advancement. Based on these challenges in the recognition and citation of software contributions and their potential impact on h-index accumulation, we hypothesize:

*H3: The frequency with which individual researchers contribute code to their research projects negatively correlates with their h-index.*

# Data and Methods
We examine the relationship between software contributions and scientific credit through a three-step process: (1) building a dataset of linked scientific articles and code repositories; (2) developing a predictive model to match article authors with developer accounts; and, (3) analyzing patterns in these relationships.

Our dataset integrates article-repository pairs from four sources, each with explicit mechanisms for code sharing: the Journal of Open Source Software (JOSS) and SoftwareX require code repositories as part of publication, Papers with Code directly connects preprints from ArXiv with software implementations, and Public Library of Science (PLOS) articles include mandatory data and code availability statements that we mined for repository links. We focused exclusively on GitHub-hosted repositories, which represent the predominant platform for scientific software sharing [@Cao2023TheRO; @escamilla2022riseofgithub]. For each article in our corpus, we resolved the source DOI via Semantic Scholar to ensure we captured its latest version and then extracted publication metadata and author metrics through OpenAlex. Finally, we collected information about each code repository and the repository's contributors via the GitHub API. A data collection and processing workflow diagram is available in @fig-workflow-diagram. All data was collected between October and November 2024[^2].

[^2]: The Journal of Open Source Software (JOSS) is available at <https://joss.theoj.org/>. SoftwareX articles are available at <https://www.sciencedirect.com/journal/softwarex/> and SoftwareX repositories are available at <https://github.com/ElsevierSoftwareX/>. Public Library of Science (PLOS) is available at <https://plos.org/> and article data is available via the `allofplos` Python package (<https://github.com/PLOS/allofplos/>). Papers with Code is available at <https://paperswithcode.com/> and data for links between papers and code is available at <https://paperswithcode.com/about/>. Documentation for the Semantic Scholar API is available at <https://api.semanticscholar.org/>, documentation for the OpenAlex API is available at <https://docs.openalex.org/>, and documentation for the GitHub API is available at <https://docs.github.com/en/rest/>.

Articles collected from JOSS and SoftwareX were labeled as "software articles," articles obtained from PLOS were labeled as "research articles," and articles from Papers with Code were labeled as either "preprint" or "research article" based on their document type from OpenAlex. While Papers with Code data is largely tied to ArXiv preprints, because of our DOI resolution process, we were able to identify a subset of these articles that had been published in a journal and were thus labeled as "research articles" by OpenAlex[^3]. Article domain classifications (e.g., Health Sciences, Life Sciences, Physical Sciences, and Social Sciences) were obtained from OpenAlex. While each article can be associated to multiple "topics", we utilize the primary topic and its associated domain for our analyses[^4].

[^3]: Papers with Code (arXiv) preprints likely include some number of software articles but without a clear and consistent mechanism to identify these articles, but we are unable to label them as such. We discuss this limitation further in @sec-discussion. Further, while some PLOS, JOSS, and SoftwareX articles may also have a preprinted version, we select and analyze the published version of the article when one is available at the time of data processing. This is made possible via the DOI resolution process using Semantic Scholar.

[^4]: OpenAlex documentation for concepts, topics, fields, and domains is available at <https://help.openalex.org/hc/en-us/articles/24736129405719-Topics/>

```{python}
exp_results = sci_soft_models_data.load_experimental_training_results()

# Remove the "time_pred" and "epoch_val" columns
exp_results = exp_results.drop(columns=["time_pred", "epoch_val"])

# Round accuracy, precision, recall, and f1 to 3 decimal places
exp_results = exp_results.round(
    {
        "accuracy": 3,
        "precision": 3,
        "recall": 3,
        "f1": 3,
    }
)

# Replace "no-optional-data" with "n/a"
exp_results["fieldset"] = exp_results["fieldset"].replace(
    "no-optional-data", "n/a"
)

# Str replace references to "dev_" in "fieldset" column
exp_results["fieldset"] = exp_results["fieldset"].str.replace("dev_", "")

# Str replace "_" with " " in "fieldset" column
exp_results["fieldset"] = exp_results["fieldset"].str.replace("_", " ")

# Str split fieldset values on "-" and rejoin with ", "
exp_results["fieldset"] = exp_results["fieldset"].str.split("-").apply(
    lambda x: ", ".join(x)
)

# Rename fieldset column to "Optional Features"
exp_results = exp_results.rename(columns={"fieldset": "Optional Feats."})

# Capitalize column names
exp_results.columns = exp_results.columns.str.title()

# Get best model f1 and get the accuracy, precision, recall, and f1 for that model
best_model_idx = exp_results["F1"].idxmax()
best_model_acc = exp_results.loc[best_model_idx, "Accuracy"]
best_model_prec = exp_results.loc[best_model_idx, "Precision"]
best_model_rec = exp_results.loc[best_model_idx, "Recall"]
best_model_f1 = exp_results.loc[best_model_idx, "F1"]
```

To match article authors with repository developer accounts, we developed a machine-learning approach using transformer-based architectures. Specifically, we use transformers to overcome entity matching challenges such as when exact name or email matching is insufficient due to formatting variations and incomplete information (e.g., "J. Doe" vs. "Jane Doe" in publications or use of institutional versus personal email addresses). When exact matching fails, there is typically high semantic overlap between an author's name and developer account details (i.e., username, name, and email) that transformer models can leverage. We created a gold-standard dataset of 2,999 annotated author-developer account pairs from JOSS publications, where two independent reviewers classified each pair as matching or non-matching. After systematic evaluation of three transformer architectures with various feature combinations, our optimal model (fine-tuned DeBERTa-v3-base including developer account username and display name in the training data) achieved a binary F1 score of `{python} float(best_model_f1)`, with `{python} float(best_model_prec)` precision and `{python} float(best_model_rec)` recall (positive = "match")[^5]. Applying our model across all article-repository pairs yielded a large-scale dataset linking scientific authors and code contributors.

[^5]: A detailed comparison of models and feature sets, and an evaluation of model performance across non-JOSS author-developer pairs are provided in Table S1 and Table S2 of the Supplementary Material.

Our complete dataset, named the "Research Software Graph" (`rs-graph-v1`), contains `{python} print_ready_m2m_doc_repo_links_count` article-repository pairs. However, `{python} print_ready_m2m_to_1to1_doc_repo_links_dropped` article-repository pairs form many-to-many relationships in which the same article is linked to multiple repositories or the same repository is linked to multiple articles. The median number of repositories per article is `{python} print_ready_m2m_median_repos` (95th percentile: `{python} print_ready_m2m_95th_percentile_repos`, 97th percentile: `{python} print_ready_m2m_97th_percentile_repos`, 99th percentile: `{python} print_ready_m2m_99th_percentile_repos`). The median number of articles per repository is `{python} print_ready_m2m_median_docs` (95th percentile: `{python} print_ready_m2m_95th_percentile_docs`, 97th percentile: `{python} print_ready_m2m_97th_percentile_docs`, 99th percentile: `{python} print_ready_m2m_99th_percentile_docs`).

To ensure that our analysis focuses on clear, unambiguous relationships between articles and repositories, prior to analysis we utilize a partial `rs-graph-v1` dataset which filters out any articles or repositories associated to multiple article-repository pairs. This filtering step removes `{python} print_ready_m2m_to_1to1_doc_repo_links_dropped` article-repository pairs. As shown in @tbl-rs-graph-overall-counts, the complete one-to-one article-repository dataset contains 138,596 unique article-repository pairs spanning multiple domains and publication types (`{python} article_repo_pairs_per_source["joss"]` unique articles, repositories, and pairs from JOSS, `{python} article_repo_pairs_per_source["plos"]` from PLOS, `{python} article_repo_pairs_per_source["pwc"]` from Papers with Code, and `{python} article_repo_pairs_per_source["softwarex"]` from SoftwareX). Additionally, the one-to-one dataset includes information for 295,806 distinct authors and 152,170 developer accounts. The one-to-one dataset includes 90,086 author-developer account relationships, creating a unique resource for investigating code contribution patterns in scientific teams. This dataset enables systematic examination of how software development work relates to scientific recognition and career trajectories. The complete `rs-graph-v1` dataset (<https://doi.org/10.7910/DVN/KPYVI1>), the trained model (<https://huggingface.co/evamxb/dev-author-em-clf>), and a supporting inference library for using the model: [sci-soft-models](https://github.com/evamaxfield/sci-soft-models), are made publicly available to support further research.

```{mermaid}
%%| label: fig-workflow-diagram
%%| fig-cap: Data Gathering and Processing Workflow. We begin by gathering article-repository pairs from PLOS, JOSS, SoftwareX, and Papers with Code, retaining only pairs where the source code repository is hosted on GitHub. For each article-repository pair, we retrieve the DOI for the most recent version of the article via the Semantic Scholar API, then obtain the article's metadata, author information, and bibliometric data from OpenAlex. In parallel, we collect the source code repository's metadata and contributor information using the GitHub API. After retrieving both article and repository information, we apply our trained author-developer matching model across all possible combinations of article authors and repository contributors for each article-repository pair. Finally, we store all retrieved information and the matched author-developer pairs in a SQLite database. Article-repository pair counts are approximate because there are no snapshots of these databases at a single point in time. The estimates are based on counts from each data source taken in October 2025.
%%| fig-height: 7
%%| fig-align: center

flowchart TB

%% sources %%
plos["PLOS<br/>(n~60,000 pairs)"] --> unfiltered[Unfiltered Article-Repository Pairs]
softwarex["SoftwareX<br/>(n~700 pairs)"] --> unfiltered
joss["JOSS<br/>(n~3,000 pairs)"] --> unfiltered
pwc["Papers with Code<br/>(n~180,000 pairs)"] --> unfiltered

%% filtering %%
unfiltered --> |Filter non-GitHub Article-Repository Pairs| dataset[GitHub-only Article-Repository Pairs]

%% article processing %%
dataset --> s2[DOI Resolution with Semantic Scholar]
s2 --> openalex[Article Metadata, Author Information, and Bibliometrics Retrieved from OpenAlex]

%% repo processing %%
dataset --> gh-api[Repository Metadata and Contributor Information Retrieved from GitHub]

%% merge %%
openalex --> core-dataset[Metadata Enriched Article-Repository Dataset]
gh-api --> core-dataset

%% author-developer matching %%
subgraph admatching[" "]
    direction TB
	
	author1[Author] <-..-> contrib1[Code Contributor]
	author2[Author] <--> |Match| contrib1
	author3[Author] <-..-> contrib1
	author4[Author] <-..-> contrib1
	author1 <--> |Match| contrib2[Code Contributor]
	author2 <-..-> contrib2
	author3 <-..-> contrib2
	author4 <-..-> contrib2
	
	linkStyle 11,14 stroke:green,color:green;
end

core-dataset --> |Match Authors and Developers in Each Article-Repository Pair| admatching

admatching --> |Store Data for Articles, Repositories, Authors, Code Contributors, Matched Individuals| final-dataset[("Final Dataset 'rs-graph-v1'")]

style admatching fill: lightgrey
```

```{python}
# Compute stats
doc_type_stats = reduced_doc_types.groupby("reduced_doc_type").apply(
    lambda x: {
        "doc_type": x.name,
        "n_article_repo_pairs": len(x),
        "n_authors": merged_doc_repo_links_documents_document_contributors.loc[
            merged_doc_repo_links_documents_document_contributors["document_id"].isin(
                x["document_id"]
            )
        ]["researcher_id"].nunique(),
        "n_devs": merged_doc_repo_links_documents_repository_contributors.loc[
            merged_doc_repo_links_documents_repository_contributors["document_id"].isin(
                x["document_id"]
            )
        ]["developer_account_id"].nunique(),
    },
    include_groups=False,
)

# Compute stats for access status
access_stats = []
for access_status_int, access_status_name in [
    (0, "Closed"),
    (1, "Open"),
]:
    # Get total article-repo pairs
    access_stats.append(
        {
            "access_status": access_status_name,
            "n_article_repo_pairs": len(
                merged_doc_repo_links_documents[
                    merged_doc_repo_links_documents["is_open_access"]
                    == access_status_int
                ]
            ),
            "n_authors": merged_doc_repo_links_documents_document_contributors.loc[
                merged_doc_repo_links_documents_document_contributors["is_open_access"]
                == access_status_int
            ]["researcher_id"].nunique(),
            "n_devs": merged_doc_repo_links_documents_repository_contributors.loc[
                merged_doc_repo_links_documents_repository_contributors[
                    "is_open_access"
                ]
                == access_status_int
            ]["developer_account_id"].nunique(),
        }
    )

# Compute totals
total_article_repo_pairs = len(doc_repo_links)
total_authors = merged_document_contributor_doc_repo_links["researcher_id"].nunique()
total_devs = merged_repository_contributor_doc_repo_links[
    "developer_account_id"
].nunique()
```

::: {.content-visible when-format="html"}
```{python}
def format_number(num):
    return "{:,}".format(num)

def _get_html_for_counts_table(
    domain_stats,
    doc_type_stats,
    access_stats,
    data_source_stats,
    total_article_repo_pairs,
    total_authors,
    total_devs,
):
    # Construct multi-row span HTML table
    # Columns should be: "n_article_repo_pairs", "n_authors", "n_devs"
    # Rows should be:
    # "By Data Source", "By Domain", "By Document Type", "By Access Status", and "Total"

    # HTML templates
    stats_piece_inital_row_template = """
    <tr>
    <td rowspan="{n_rows}">{row_name}</td>
    <td>{value_name}</td>
    <td>{article_repo_pairs}</td>
    <td>{authors}</td>
    <td>{devs}</td>
    </tr>
    """.strip()

    stats_piece_subsequent_row_template = """
    <tr>
    <td>{value_name}</td>
    <td>{article_repo_pairs}</td>
    <td>{authors}</td>
    <td>{devs}</td>
    </tr>
    """.strip()

    # Convert all numbers to strings with commas
    for stats_portion in [
        domain_stats,
        doc_type_stats,
        access_stats,
        data_source_stats,
    ]:
        for stats_piece in stats_portion:
            stats_piece["n_article_repo_pairs"] = (
                format_number(stats_piece["n_article_repo_pairs"])
                if isinstance(stats_piece["n_article_repo_pairs"], int)
                else stats_piece["n_article_repo_pairs"]
            )
            stats_piece["n_authors"] = (
                format_number(stats_piece["n_authors"])
                if isinstance(stats_piece["n_authors"], int)
                else stats_piece["n_authors"]
            )
            stats_piece["n_devs"] = (
                format_number(stats_piece["n_devs"])
                if isinstance(stats_piece["n_devs"], int)
                else stats_piece["n_devs"]
            )

    # Convert the totals
    total_article_repo_pairs = format_number(total_article_repo_pairs)
    total_authors = format_number(total_authors)
    total_devs = format_number(total_devs)

    # Iter over stats portions (and total)
    stats_portions_html = []
    for stats_portion, stats_name, value_key in [
        (domain_stats, "<b>By Domain</b>", "domain"),
        (doc_type_stats, "<b>By Document Type</b>", "doc_type"),
        (access_stats, "<b>By Access Status</b>", "access_status"),
        (data_source_stats, "<b>By Data Source</b>", "data_source"),
        (
            [
                {
                    "empty": "",
                    "n_article_repo_pairs": f"<b>{total_article_repo_pairs}</b>",
                    "n_authors": f"<b>{total_authors}</b>",
                    "n_devs": f"<b>{total_devs}</b>",
                }
            ],
            "<b>Total</b>",
            "empty",
        ),
    ]:
        # Order by value_key
        if value_key != "empty":
            stats_portion = sorted(
                stats_portion, key=lambda x: x[value_key]
            )

        stats_portion_html = []
        for i, stats_piece in enumerate(stats_portion):
            if i == 0:
                stats_portion_html.append(
                    stats_piece_inital_row_template.format(
                        n_rows=len(stats_portion),
                        row_name=stats_name,
                        value_name=stats_piece[value_key],
                        article_repo_pairs=stats_piece["n_article_repo_pairs"],
                        authors=stats_piece["n_authors"],
                        devs=stats_piece["n_devs"],
                    )
                )
            else:
                stats_portion_html.append(
                    stats_piece_subsequent_row_template.format(
                        value_name=stats_piece[value_key],
                        article_repo_pairs=stats_piece["n_article_repo_pairs"],
                        authors=stats_piece["n_authors"],
                        devs=stats_piece["n_devs"],
                    )
                )

        stats_portions_html.append("\n".join(stats_portion_html))

    # Concat and wrap in table
    stats_table_html = f"""
    <table>
    <tr>
        <th><b>Category</b></th>
        <th><b>Subset</b></th>
        <th><b>Article-Repository Pairs</b></th>
        <th><b>Authors</b></th>
        <th><b>Developers</b></th>
    </tr>
    {" ".join(stats_portions_html)}
    </table>
    """.strip()

    return stats_table_html
```

```{python}
#| label: tbl-rs-graph-overall-counts
#| tbl-cap: "Counts of Article-Repository Pairs, Authors, and Developers by Data Sources, Domains, Document Types, and Access Status in the Complete, Unfiltered Dataset."

stats_table_html = _get_html_for_counts_table(
    domain_stats=domain_stats,
    doc_type_stats=doc_type_stats,
    access_stats=access_stats,
    data_source_stats=data_source_stats,
    total_article_repo_pairs=total_article_repo_pairs,
    total_authors=total_authors,
    total_devs=total_devs,
)

IPython.display.HTML(stats_table_html)
```
:::

::: {.content-visible when-format="pdf"}
```{python}
def _get_latex_for_counts_table(
    caption,
    label,
    domain_stats,
    doc_type_stats,
    access_stats,
    data_source_stats,
    total_article_repo_pairs,
    total_authors,
    total_devs,
):
    # LaTeX templates
    stats_piece_initial_row_template = """    \\multirow{{{n_rows}}}{{*}}{{\\textbf{{{row_name}}}}} & \\cellcolor{{gray!10}}{value_name} & \\cellcolor{{gray!10}}{article_repo_pairs} & \\cellcolor{{gray!10}}{authors} & \\cellcolor{{gray!10}}{devs} \\\\"""

    stats_piece_subsequent_row_template = """    & {value_name} & {article_repo_pairs} & {authors} & {devs} \\\\"""

    # Table header and footer templates
    table_header_start = """\\begin{{table}}
    \\centering
    \\small
    \\caption{{{caption}}}
    \\label{{{label}}}
    \\begin{{tabular}}{{llrrr}}
    \\toprule
    \\textbf{{Category}} & \\textbf{{Subset}} & \\textbf{{Article-Repository Pairs}} & \\textbf{{Authors}} & \\textbf{{Developers}} \\\\
    \\midrule""".format(
        caption=caption,
        label=label,
    )

    table_footer = """\\bottomrule
    \\end{tabular}
    \\end{table}"""

    # Convert all numbers to strings with commas
    for stats_portion in [
        domain_stats,
        doc_type_stats,
        access_stats,
        data_source_stats,
    ]:
        for stats_piece in stats_portion:
            stats_piece["n_article_repo_pairs"] = (
                format_number(stats_piece["n_article_repo_pairs"])
                if isinstance(stats_piece["n_article_repo_pairs"], int)
                else stats_piece["n_article_repo_pairs"]
            )
            stats_piece["n_authors"] = (
                format_number(stats_piece["n_authors"])
                if isinstance(stats_piece["n_authors"], int)
                else stats_piece["n_authors"]
            )
            stats_piece["n_devs"] = (
                format_number(stats_piece["n_devs"])
                if isinstance(stats_piece["n_devs"], int)
                else stats_piece["n_devs"]
            )

    # Convert the totals
    total_article_repo_pairs = format_number(total_article_repo_pairs)
    total_authors = format_number(total_authors)
    total_devs = format_number(total_devs)

    # Generate table content
    stats_portions_latex = []
    for stats_portion, stats_name, value_key in [
        (domain_stats, "By Domain", "domain"),
        (doc_type_stats, "By Document Type", "doc_type"),
        (access_stats, "By Access Status", "access_status"),
        (data_source_stats, "By Data Source", "data_source"),
        (
            [
                {
                    "empty": "",
                    "n_article_repo_pairs": total_article_repo_pairs,
                    "n_authors": total_authors,
                    "n_devs": total_devs,
                }
            ],
            "Total",
            "empty",
        ),
    ]:
        # Order by value_key
        if value_key != "empty":
            stats_portion = sorted(
                stats_portion, key=lambda x: x[value_key]
            )

        stats_portion_latex = []
        if stats_name == "Total":
            stats_portion_latex.append(
                f"    \\textbf{{Total}} & & \\textbf{{{stats_portion[0]['n_article_repo_pairs']}}} & \\textbf{{{stats_portion[0]['n_authors']}}} & \\textbf{{{stats_portion[0]['n_devs']}}} \\\\"
            )
        else:
            # Add the first row with the category label and colored cells
            first_piece = stats_portion[0]
            stats_portion_latex.append(
                stats_piece_initial_row_template.format(
                    n_rows=len(stats_portion),
                    row_name=stats_name,
                    value_name=first_piece[value_key],
                    article_repo_pairs=first_piece["n_article_repo_pairs"],
                    authors=first_piece["n_authors"],
                    devs=first_piece["n_devs"],
                ).rstrip()
            )
            
            # Add subsequent rows with alternating colors
            for i, stats_piece in enumerate(stats_portion[1:]):
                color_cmd = "\\cellcolor{gray!10}" if i % 2 == 1 else ""
                stats_portion_latex.append(
                    f"    & {color_cmd}{stats_piece[value_key]} & {color_cmd}{stats_piece['n_article_repo_pairs']} & {color_cmd}{stats_piece['n_authors']} & {color_cmd}{stats_piece['n_devs']} \\\\"
                )

        section_latex = "\n".join(stats_portion_latex)
        if stats_name != "Total":
            section_latex += "\\midrule"
        stats_portions_latex.append(section_latex)

    # Combine all parts
    stats_table_latex = f"""{table_header_start}
    {"\n".join(stats_portions_latex)}
    {table_footer}"""

    return stats_table_latex
```

```{python}
stats_table_latex = _get_latex_for_counts_table(
    caption="Counts of Article-Repository Pairs, Authors, and Developers by Data Sources, Domains, Document Types, and Access Status in the Complete, Unfiltered Dataset.",
    label="tbl-rs-graph-overall-counts",
    domain_stats=domain_stats,
    doc_type_stats=doc_type_stats,
    access_stats=access_stats,
    data_source_stats=data_source_stats,
    total_article_repo_pairs=total_article_repo_pairs,
    total_authors=total_authors,
    total_devs=total_devs,
)

IPython.display.Latex(stats_table_latex)
```
:::

# Analysis of Code Contributor Authorship and Development Dynamics of Research Teams

## Software Development Dynamics Within Research Teams

```{python}
# Filter down repositories to only include those ids
repositories_subset_with_code = repositories.loc[repositories["id"].isin(repositories_with_code)]
doc_repo_links_with_code = doc_repo_links.loc[doc_repo_links["repository_id"].isin(repositories_with_code)]
docs_with_code = documents.loc[documents["id"].isin(doc_repo_links_with_code["document_id"])]

# Create subset documents
docs_w_1_citation = docs_with_code.loc[docs_with_code["cited_by_count"] >= 1].copy()

# Take sample?
if USE_SAMPLE:
    docs_w_1_citation = docs_w_1_citation.sample(frac=0.02, random_state=12)

# Subset to only certain columns
docs_w_1_citation = docs_w_1_citation[
    [
        "id",
        "publication_date",
        "cited_by_count",
        "fwci",
        "is_open_access",
    ]
]

# Rename id to document_id
docs_w_1_citation = docs_w_1_citation.rename(columns={"id": "document_id"})

# Merge repository id in
docs_w_1_citation = docs_w_1_citation.merge(
    doc_repo_links[[
        "document_id",
        "repository_id",
    ]],
    left_on="document_id",
    right_on="document_id",
)

# Merge in document details (domain, document type)
docs_w_1_citation = (
    docs_w_1_citation.merge(
        document_topics[["document_id", "topic_id"]],
        left_on="document_id",
        right_on="document_id",
    )
    .merge(
        repositories[["id", "creation_datetime", "last_pushed_datetime"]],
        left_on="repository_id",
        right_on="id",
    )
    .drop(
        columns=["id"],
    )
    .merge(
        topics[["id", "domain_name"]],
        left_on="topic_id",
        right_on="id",
    )
    .drop(
        columns=["id", "topic_id"],
    )
    .merge(
        reduced_doc_types,
        left_on="document_id",
        right_on="document_id",
    )
    .rename(
        columns={
            "domain_name": "domain",
            "reduced_doc_type": "article_type",
        }
    )
)

# Drop any documents that have more than one repository (and vice versa)
docs_w_1_citation = docs_w_1_citation.drop_duplicates(
    subset=["document_id"], keep=False
)
docs_w_1_citation = docs_w_1_citation.drop_duplicates(
    subset=["repository_id"], keep=False
)

# Iter over articles and get the team composition info
team_composition_rows = []
relationships_removed_from_confidence_thresh = set()
for _, row in docs_w_1_citation.iterrows():
    # Get a boolean value for "no pushes after publication"
    repo_details = repositories.loc[repositories["id"] == row["repository_id"]].iloc[0]

    # Get the number of authors
    author_ids = document_contributors.loc[
        document_contributors["document_id"] == row["document_id"]
    ]["researcher_id"].unique()
    n_authors = len(author_ids)

    # Get the number of devs
    dev_ids = repository_contributors.loc[
        repository_contributors["repository_id"] == row["repository_id"]
    ]["developer_account_id"].unique()
    n_devs = len(dev_ids)

    # Get the set of researcher_dev_links for the authors
    author_dev_links = researcher_dev_links.loc[
        researcher_dev_links["researcher_id"].isin(author_ids)
    ].sort_values("predictive_model_confidence", ascending=False)

    # Drop duplicates by developer_account_id (keeping first)
    # as we may have accidently matched the same dev to the multiple authors
    author_dev_links = author_dev_links.drop_duplicates(
        subset=["developer_account_id"],
        keep="first",
    )

    # Drop any author dev links that have less than 97% confidence
    author_dev_links_filtered = author_dev_links.loc[
        author_dev_links["predictive_model_confidence"] >= 0.97
    ]
    for _, relationship_row in author_dev_links.loc[
        author_dev_links["predictive_model_confidence"] < 0.97
    ].iterrows():
        # If the relationship was removed, add it to the set
        relationships_removed_from_confidence_thresh.add(
            (relationship_row["researcher_id"], relationship_row["developer_account_id"])
        )

    # Get the set of dev_researcher_links for the devs
    dev_researcher_links = researcher_dev_links.loc[
        researcher_dev_links["developer_account_id"].isin(dev_ids)
    ].sort_values("predictive_model_confidence", ascending=False)

    # Drop duplicates by dev_id (keeping first)
    # as we may have accidently matched the same author to the multiple devs
    dev_researcher_links = dev_researcher_links.drop_duplicates(
        subset=["researcher_id"],
        keep="first",
    )

    # Drop any dev researcher links that have less than 97% confidence
    dev_researcher_links_filtered = dev_researcher_links.loc[
        dev_researcher_links["predictive_model_confidence"] >= 0.97
    ]
    for _, relationship_row in dev_researcher_links.loc[
        dev_researcher_links["predictive_model_confidence"] < 0.97
    ].iterrows():
        # If the relationship was removed, add it to the set
        relationships_removed_from_confidence_thresh.add(
            (relationship_row["researcher_id"], relationship_row["developer_account_id"])
        )

    # Get the number of authors who were devs on this paper
    n_author_devs = 0
    n_author_non_devs = 0
    for author_id in author_ids:
        author_dev_ids = author_dev_links_filtered.loc[
            author_dev_links_filtered["researcher_id"] == author_id
        ]["developer_account_id"].unique()

        # Count
        if any(author_dev_id in dev_ids for author_dev_id in author_dev_ids):
            n_author_devs += 1
        else:
            n_author_non_devs += 1

    # Get the number of devs who aren't authors
    n_non_author_devs = 0
    for dev_id in dev_ids:
        dev_researcher_ids = dev_researcher_links_filtered.loc[
            dev_researcher_links_filtered["developer_account_id"] == dev_id
        ]["researcher_id"].unique()

        # No dev should be matched to more than 3 authors
        if len(dev_researcher_ids) > 3:
            continue

        # Count
        if not any(dev_researcher_id in author_ids for dev_researcher_id in dev_researcher_ids):
            n_non_author_devs += 1

    # Append
    team_composition_rows.append(
        {
            "document_id": row["document_id"],
            "repository_id": row["repository_id"],
            "author_ids": author_ids.tolist(),
            "dev_ids": dev_ids.tolist(),
            "n_authors": n_authors,
            "n_author_non_devs": n_author_non_devs,
            "n_author_devs": n_author_devs,
            "n_non_author_devs": n_non_author_devs,
            "n_devs": n_devs,
        }
    )

# Create dataframe
team_composition = pd.DataFrame(team_composition_rows)

# Merge with docs_w_1_citation
team_composition = team_composition.merge(
    docs_w_1_citation,
    left_on=["document_id", "repository_id"],
    right_on=["document_id", "repository_id"],
)

# Filter out papers with less than 3 authors or 1 dev
team_composition = team_composition.loc[team_composition["n_authors"] >= 3]
team_composition = team_composition.loc[team_composition["n_devs"] >= 1]

# Convert datetimes to datetime
team_composition["publication_date"] = pd.to_datetime(
    team_composition["publication_date"],
    utc=True,
)
team_composition["last_pushed_datetime"] = pd.to_datetime(
    team_composition["last_pushed_datetime"],
    utc=True,
)
team_composition["creation_datetime"] = pd.to_datetime(
    team_composition["creation_datetime"],
    utc=True,
)

# Calculate years since publication from 2024-11-01
team_composition["years_since_publication"] = (
    pd.to_datetime("2024-11-01", utc=True) - team_composition["publication_date"]
).dt.days / 365.25

# Calculate repo creation to last push
team_composition["repo_commit_duration"] = (
    team_composition["last_pushed_datetime"] - team_composition["creation_datetime"]
).dt.days / 365.25

# Create a "days_since_last_push" column
team_composition["days_from_publication_to_last_push"] = (
    team_composition["last_pushed_datetime"] - team_composition["publication_date"]
).dt.days

# Create a "days_since_last_push" column
team_composition["days_from_publication_to_last_push"] = (
    team_composition["last_pushed_datetime"] - team_composition["publication_date"]
).dt.days

# Must have a push within 90 days of publication
team_comp_no_push_after_pub = team_composition.loc[
    team_composition["days_from_publication_to_last_push"] <= 90
].copy()

# Create a "publication_year" column
team_comp_no_push_after_pub["publication_year"] = team_comp_no_push_after_pub[
    "publication_date"
].dt.year

# Drop columns that would conflict with conversion to float
team_comp_no_push_after_pub = team_comp_no_push_after_pub.drop(
    columns=[
        "publication_date",
        "last_pushed_datetime",
        "creation_datetime",
    ]
)

# Get the number of authors which would be the 97th percentile
n_authors_97th_percentile = team_comp_no_push_after_pub["n_authors"].quantile(0.97)

# Remove rows that are greater than 97th percentile for total authors
team_comp_no_push_after_pub = team_comp_no_push_after_pub.loc[
    team_comp_no_push_after_pub["n_authors"]
    <= team_comp_no_push_after_pub["n_authors"].quantile(0.97)
]

# Get columns needed for counts table
team_comp_no_push_after_pub_counts_table = team_comp_no_push_after_pub[
    [
        "document_id",
        "repository_id",
        "author_ids",
        "dev_ids",
        "article_type",
        "domain",
        "is_open_access",
    ]
].copy()

# Drop author_ids and dev_ids from original dataframe
team_comp_no_push_after_pub = team_comp_no_push_after_pub.drop(
    columns=["author_ids", "dev_ids"]
)

# Add dummies
team_comp_no_push_after_pub_dummies = pd.get_dummies(
    team_comp_no_push_after_pub,
    columns=["article_type", "domain"],
    drop_first=True,
)

# Cast all to float
team_comp_no_push_after_pub_dummies = team_comp_no_push_after_pub_dummies.astype(float)

# Create metrics for overall
metric_str_fmt = "{met_mean:.1f} ± {met_std:.1f}"
total_auths = metric_str_fmt.format(
    met_mean=team_comp_no_push_after_pub["n_authors"].mean(),
    met_std=team_comp_no_push_after_pub["n_authors"].std(),
)
total_auth_devs = metric_str_fmt.format(
    met_mean=team_comp_no_push_after_pub["n_author_devs"].mean(),
    met_std=team_comp_no_push_after_pub["n_author_devs"].std(),
)
total_auth_non_devs = metric_str_fmt.format(
    met_mean=team_comp_no_push_after_pub["n_author_non_devs"].mean(),
    met_std=team_comp_no_push_after_pub["n_author_non_devs"].std(),
)
total_non_auth_devs = metric_str_fmt.format(
    met_mean=team_comp_no_push_after_pub["n_non_author_devs"].mean(),
    met_std=team_comp_no_push_after_pub["n_non_author_devs"].std(),
)

# Get the number of papers which have great than zero non_author_devs
n_papers_w_non_auth_devs = len(team_comp_no_push_after_pub.loc[
    team_comp_no_push_after_pub["n_non_author_devs"] > 0
])
pct_papers_w_non_auth_devs = round(
    (n_papers_w_non_auth_devs / len(team_comp_no_push_after_pub)) * 100, 1
)
median_non_author_devs_for_papers_w_non_auth_devs = team_comp_no_push_after_pub.loc[
    team_comp_no_push_after_pub["n_non_author_devs"] > 0
]["n_non_author_devs"].median()
mean_non_author_devs_for_papers_w_non_auth_devs = metric_str_fmt.format(
    met_mean=team_comp_no_push_after_pub.loc[
        team_comp_no_push_after_pub["n_non_author_devs"] > 0
    ]["n_non_author_devs"].mean(),
    met_std=team_comp_no_push_after_pub.loc[
        team_comp_no_push_after_pub["n_non_author_devs"] > 0
    ]["n_non_author_devs"].std(),
)

# Merge counts table with dataset sources
team_comp_no_push_after_pub_counts_table = team_comp_no_push_after_pub_counts_table.merge(
    doc_repo_links[[
        "document_id",
        "repository_id",
        "dataset_source_id",
    ]],
    on=["document_id", "repository_id"],
    how="left",
).merge(
    dataset_sources.rename(
        columns={
            "id": "dataset_source_id", "name": "dataset_source_name"
        }
    ),
    on="dataset_source_id",
    how="left",
)

# Get counts by:
# - domain
# - article type
# - open access status
# - dataset source
# - total

def _get_counts_by_column(
    df: pd.DataFrame,
    column_name: str,
    category: str,
    subset_replace: dict | None = None,
) -> dict:
    counts = []
    for value in df[column_name].unique():
        subset = df.loc[df[column_name] == value]

        # Replace value if subset_replace is provided
        if subset_replace is not None and value in subset_replace:
            value = subset_replace[value]

        # Get counts
        author_ids = set(subset["author_ids"].explode().dropna().unique())
        dev_ids = set(subset["dev_ids"].explode().dropna().unique())

        # Append counts
        counts.append({
            category: value,
            "n_article_repo_pairs": len(subset),
            "n_authors": len(author_ids),
            "n_devs": len(dev_ids),
        })

    return counts

team_comp_no_push_after_pub_counts_domain = _get_counts_by_column(
    team_comp_no_push_after_pub_counts_table,
    "domain",
    "domain",
)
team_comp_no_push_after_pub_counts_article_type = _get_counts_by_column(
    team_comp_no_push_after_pub_counts_table,
    "article_type",
    "doc_type",
)
team_comp_no_push_after_pub_counts_open_access = _get_counts_by_column(
    team_comp_no_push_after_pub_counts_table,
    "is_open_access",
    "access_status",
    subset_replace={
        0: "Closed",
        1: "Open",
    },
)
team_comp_no_push_after_pub_counts_dataset_source = _get_counts_by_column(
    team_comp_no_push_after_pub_counts_table,
    "dataset_source_name",
    "data_source",
)

team_comp_no_push_after_pub_total_pairs = len(
    team_comp_no_push_after_pub_counts_table
)
team_comp_no_push_after_pub_total_authors = team_comp_no_push_after_pub_counts_table[
    "author_ids"
].explode().dropna().nunique()
team_comp_no_push_after_pub_total_devs = team_comp_no_push_after_pub_counts_table[
    "dev_ids"
].explode().dropna().nunique()

print_ready_dataset_size = "{:,}".format(len(team_comp_no_push_after_pub))

print_ready_n_papers_w_non_auth_devs =  "{:,}".format(n_papers_w_non_auth_devs)
```

Understanding the composition and dynamics of software development teams provides essential context for analyzing how code contributions relate to scientific recognition and impact. To ensure reliable analysis, we focus on a subset of our article-repository pairs that meet several filtering conditions. First, to ensure that we aren't analyzing "data repositories" (i.e. GitHub repositories which only store CSV, Parquet, or other dataset related file formats), we filter out any article-repository pairs that don't have any programming language files[^6]. Next, to ensure that the research has received a basic level of engagement from the scientific community, we remove any article-repository pairs which do not have at least one citation. We then require that repository commit activity stop before 90 days past the article publication date. Disallowing long-term projects ensures we do not include projects that may add additional code contributors later while still allowing a grace period during which developers can update repositories with additional documentation and publication information. We then subset the data to only include article-repository pairs with research teams of typical size by removing those with fewer than three authors and more than `{python} int(n_authors_97th_percentile)` authors, the 97th percentile for research team size. Finally, we filter out any predicted author-developer pairs with a confidence score of less than 0.97 in order to improve robustness of our downstream analysis[^7]. This filtering process results in a dataset of `{python} print_ready_dataset_size` article-repository pairs. Detailed counts by data source, domain, document type, and access status are provided in Table S4 of the Supplementary Material.

[^6]: We use the list of programming languages used by the GitHub platform via the [Linguist software](https://github.com/github-linguist/linguist), and the GitHub API to retrieve the bytes of code per-language within each repository. We remove article-repository pairs which have a non-zero number of bytes of code for programming language files.

[^7]: Figure S1 in the Supplementary Material shows the distribution of predictive model confidence scores for author-developer pairs to justify this threshold. We chose the 0.97 threshold to ensure that we only include high-confidence matches while retaining a large proportion of the data (87,175 author-developer pairs) as only 2,911 author-developer-account pairs have a confidence less than 0.97 in the whole unfiltered dataset.

Within this filtered dataset, we categorized individuals into three groups: code-contributing authors (CC-A) who both authored papers and committed code to associated repositories[^8], non-code-contributing authors (NCC-A) who authored papers but showed no evidence of code contributions, and code-contributing non-authors (CC-NA) who contributed code but received no authorship recognition. This categorization revealed that papers in our dataset typically have `{python} total_auths` total authors, with `{python} total_auth_devs` code-contributing authors and `{python} total_auth_non_devs` non-code-contributing authors. Beyond the author list, papers averaged `{python} total_non_auth_devs` code-contributing non-authors. @fig-team-composition details these distributions by domain, article type, open access status, and overall across the entire filtered analysis set[^9].

[^8]: We define code-contributing authors as those who have at least one code commit to the repository associated with the article-repository pair.

[^9]: Means and standard deviations for each distribution and subset of team composition are provided in Table S5 of the Supplementary Material.

Perhaps most striking is our finding that `{python} print_ready_n_papers_w_non_auth_devs` papers (\~`{python} pct_papers_w_non_auth_devs`% of our sample) have at least one code contributor who was not matched to any article author. Further, investigating this subset of papers, we find an average of `{python} mean_non_author_devs_for_papers_w_non_auth_devs` unmatched code contributors per paper. We constructed a random sample of 200 code-contributing non-authors (complete methodology provided in the Supplementary Material) in order to better understand these individuals and their contributions. We characterize this subset in three ways: \~39% (n=78) represent true non-authors (individuals who likely should not be matched to an author), \~30.5% (n=61) appear to be missed classifications (individuals who likely should have been matched to authors), and the remaining \~30.5% (n=61) were unclear due to limited profile information[^10]. 

Across all groups, the majority of the code-contributing non-authors made code changes rather than just documentation updates. Among true non-authors, \~77.6% (n=59) contributed code, with the top 25th percentile of these contributors contributing \~10.7% of total repository commits and \~14.4% of absolute code changes. The unclear cases showed substantially higher contribution levels— many were repository owners with extensive engagement. Yet, even among the non-owners, the median contributor accounted for \~34.6% of repository commits and \~12.7% of absolute changes. Due to the limited size of our sample (n=200 code-contributing non-authors), we do not generalize these findings to the entire population but note that they describe the diverse nature of code contribution patterns from potentially unacknowledged contributors.

[^10]: While annotation for the model training and evaluation set was done using primarily simple text information (e.g., usernames, emails, etc.), annotation conducted during the qualitative analysis of code-contributing non-authors included a more in-depth review of public profiles including any linked websites or social media profiles. This was done to gain a true best estimate for the "true", "missed", and "unclear" classifications. Additional qualitative error analysis was conducted across the set of 61 likely authors, with supporting descriptive statistics in Table S6 through Table S8 of the Supplementary Material.

These findings reveal a more complex dynamic between software development and authorship recognition than previously documented. While our finding that each paper averages only a single code-contributing author aligns with previous research showing technical tasks typically fall to first authors [@Larivire2020InvestigatingTD], the substantial contributions made by unrecognized contributors suggest systematic gaps in how scientific software development work is credited.

```{python}
# Create a copy of the team_comp_no_push_after_pub dataframe
team_comp_no_push_after_pub_counts = team_comp_no_push_after_pub.copy()

# Replace binary values in "is_open_access" to "Open Access" and "Closed Access"
team_comp_no_push_after_pub_counts["is_open_access"] = (
    team_comp_no_push_after_pub_counts.apply(
        lambda x: "Open" if x["is_open_access"] == 1 else "Closed",
        axis=1,
    )
)

# Count team composition values and always for each control variable
control_vars = {
    "is_open_access": "OA Status",
    "domain": "Domain",
    "article_type": "Article Type",
    "Overall": "Overall",
}
control_var_tables = {}
team_comp_table_rows = []
for control_var, control_display_name in control_vars.items():
    if control_var == "Overall":
        mean_table = (
            team_comp_no_push_after_pub_counts[
                ["n_authors", "n_author_non_devs", "n_author_devs", "n_non_author_devs"]
            ]
            .mean()
            .to_frame()
            .T
        )
        std_table = (
            team_comp_no_push_after_pub_counts[
                ["n_authors", "n_author_non_devs", "n_author_devs", "n_non_author_devs"]
            ]
            .std()
            .to_frame()
            .T
        )

        # For overall, we want to add a row for every row in the team_comp_no_push_after_pub_counts table
        for _, team_comp_no_push_after_pub_counts_row in team_comp_no_push_after_pub_counts.iterrows():
            team_comp_table_rows.append(
                {
                    "Control": control_display_name,
                    "Subset": "",
                    "Total Authors": team_comp_no_push_after_pub_counts_row["n_authors"],
                    "NCC-A": team_comp_no_push_after_pub_counts_row["n_author_non_devs"],
                    "CC-A": team_comp_no_push_after_pub_counts_row["n_author_devs"],
                    "CC-NA": team_comp_no_push_after_pub_counts_row["n_non_author_devs"],
                }
            )

        # Merge and format to string
        count_table_rows = []
        for _, row in mean_table.iterrows():
            std_row = std_table.loc[std_table.index == row.name]
            count_table_rows.append(
                {
                    "Overall": "",
                    "n_authors": f"{row['n_authors']:.1f} ± {std_row['n_authors'].iloc[0]:.1f}",
                    "n_author_non_devs": f"{row['n_author_non_devs']:.1f} ± {std_row['n_author_non_devs'].iloc[0]:.1f}",
                    "n_author_devs": f"{row['n_author_devs']:.1f} ± {std_row['n_author_devs'].iloc[0]:.1f}",
                    "n_non_author_devs": f"{row['n_non_author_devs']:.1f} ± {std_row['n_non_author_devs'].iloc[0]:.1f}",
                }
            )

    else:
        # Instead of taking median, let's return the mean and std in the following format
        # "mean ± std"
        mean_table = (
            team_comp_no_push_after_pub_counts.groupby(control_var)[
                ["n_authors", "n_author_non_devs", "n_author_devs", "n_non_author_devs"]
            ]
            .mean()
            .reset_index()
        )
        std_table = (
            team_comp_no_push_after_pub_counts.groupby(control_var)[
                ["n_authors", "n_author_non_devs", "n_author_devs", "n_non_author_devs"]
            ]
            .std()
            .reset_index()
        )

        # Merge and format to string
        count_table_rows = []
        for _, row in mean_table.iterrows():
            std_row = std_table.loc[std_table[control_var] == row[control_var]]
            count_table_rows.append(
                {
                    control_var: row[control_var],
                    "n_authors": f"{row['n_authors']:.1f} ± {std_row['n_authors'].iloc[0]:.1f}",
                    "n_author_non_devs": f"{row['n_author_non_devs']:.1f} ± {std_row['n_author_non_devs'].iloc[0]:.1f}",
                    "n_author_devs": f"{row['n_author_devs']:.1f} ± {std_row['n_author_devs'].iloc[0]:.1f}",
                    "n_non_author_devs": f"{row['n_non_author_devs']:.1f} ± {std_row['n_non_author_devs'].iloc[0]:.1f}",
                }
            )

        # Also add all of these rows to the team_comp_table_rows
        control_df = team_comp_no_push_after_pub_counts.groupby(control_var)[
            ["n_authors", "n_author_non_devs", "n_author_devs", "n_non_author_devs"]
        ]
        for subset_value, subset_df in control_df:
            for _, subset_row in subset_df.iterrows():
                team_comp_table_rows.append(
                    {
                        "Control": control_display_name,
                        "Subset": subset_value,
                        "Total Authors": subset_row['n_authors'],
                        "NCC-A": subset_row['n_author_non_devs'],
                        "CC-A": subset_row['n_author_devs'],
                        "CC-NA": subset_row['n_non_author_devs'],
                    }
                )

    # Create dataframe
    count_table = pd.DataFrame(count_table_rows)

    # Change name of the control_var column to "Subset"
    count_table = count_table.rename(columns={control_var: "Subset"})

    # Order columns
    count_table = count_table[
        ["Subset", "n_authors", "n_author_non_devs", "n_author_devs", "n_non_author_devs"]
    ]
    
    # Rename columns
    count_table = count_table.rename(
        columns={
            "n_authors": "Total Authors",
            "n_author_non_devs": "NCC-A",
            "n_author_devs": "CC-A",
            "n_non_author_devs": "CC-NA",
        }
    )

    # Order alphabetically
    count_table = count_table.sort_values("Subset")
    
    # Add to dictionary
    control_var_tables[control_display_name] = count_table

# Convert the mean_std_team_comp_as_table_rows to a dataframe
team_comp_table_df = pd.DataFrame(team_comp_table_rows)

# We want to pivot the table so that there are four columns: "Control", "Subset", "Contributor Type", "Count"
team_comp_table_df = team_comp_table_df.melt(
    id_vars=["Control", "Subset"],
    value_vars=["Total Authors", "NCC-A", "CC-A", "CC-NA"],
    var_name="Contributor Type",
    value_name="Count",
)
```

```{python}
#| label: fig-team-composition
#| fig-cap: Mean of Non-Code-Contributing Authors (NCC-A), Code-Contributing Authors (CC-A), and Code-Contributing Non-Authors (CC-NA) Research Team Members by Domain, Article Type, and Open Access Status. Only includes research teams from article-repository pairs with repositories that have programming language files, a most recent commit no later than 90 days after publication, and excludes research teams in the top 3% of total author sizes.

g = sns.catplot(
    data=team_comp_table_df.rename(columns={"Count": "Mean Count"}),
    x="Subset",
    y="Mean Count",
    hue="Contributor Type",
    hue_order=[
        "Total Authors",
        "NCC-A",
        "CC-A",
        "CC-NA",
    ],
    col="Control",
    col_wrap=2,
    kind="bar",
    height=3.3,
    aspect=1,
    sharey=False,
    sharex=False,
    legend=True,
)

# Rotate x labels
for ax in g.axes.flat:
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha="right")

# Move legend to below the plot
sns.move_legend(
    g,
    bbox_to_anchor=(0.4, -0.06),
    loc="upper center",
    ncol=4,
    fontsize=12,
    title_fontsize=14,
)

# Change titles
g.set_titles("{col_name}")

# Remove x label and set y label
for ax in g.axes.flat:
    ax.set_xlabel("")
    ax.set_ylabel("Mean Count")

# Add space between plots
g.fig.subplots_adjust(hspace=1.2, wspace=0.5)
```

When examining these patterns over time and across different team sizes (@fig-contributor-type-by-time-and-size), we found that the number of code-contributing authors and unrecognized contributors has remained relatively stable. This suggests that while the exclusion of code contributors from authorship is not worsening, it represents a persistent feature of scientific software development rather than a historical artifact or transition period in research practices. Similarly, the number of code-contributing non-authors remains constant even as team size grows, indicating that larger research teams do not necessarily adopt more inclusive authorship practices for code contributors despite representing broader collaborative efforts.

```{python}
#| label: fig-contributor-type-by-time-and-size
#| fig-cap: "Average number of contributors per article, by contribution type: Non-Code-Contributing Authors (NCC-A), Code-Contributing Authors (CC-A), and Code-Contributing Non-Authors (CC-NA). Split into, A) the year the article was published and B) the total number of authors included in the article. Only includes research teams from article-repository pairs with repositories that have programming language files, a most recent commit no later than 90 days after publication, and excludes research teams in the top 3% of total author sizes for publication years with 50 or more articles. Shaded areas show the 95% confidence interval for the mean."

# Make a copy for team size comparison
team_comp_by_year_and_size = team_comp_no_push_after_pub.copy()

# Rename columns
team_comp_by_year_and_size = team_comp_by_year_and_size.rename(
    columns={
        "n_authors": "Total Authors",
        "publication_year": "Publication Year",
        "n_author_devs": "CC-A",
        "n_author_non_devs": "NCC-A",
        "n_non_author_devs": "CC-NA",
    }
)

# Get value count of publication year
year_counts = team_comp_no_push_after_pub["publication_year"].value_counts()

# Drop years with less than 50 publications
team_comp_by_year_and_size = team_comp_by_year_and_size.loc[
    team_comp_no_push_after_pub["publication_year"].isin(
        year_counts.loc[lambda x: x >= 50].index
    )
]

# First separate out the year and authors
team_comp_by_year_and_size = team_comp_by_year_and_size.melt(
    id_vars=[
        "document_id",
        "NCC-A",
        "CC-A",
        "CC-NA",
    ],
    value_vars=[
        "Publication Year",
        "Total Authors",
    ],
    var_name="comparison_var",
    value_name="value",
)

# Melt again to get the contributor type
team_comp_by_year_and_size = team_comp_by_year_and_size.melt(
    id_vars=[
        "document_id",
        "comparison_var",
        "value",
    ],
    value_vars=[
        "NCC-A",
        "CC-A",
        "CC-NA",
    ],
    var_name="Contributor Type",
    value_name="Count",
)

# Plot
g = sns.relplot(
    data=team_comp_by_year_and_size,
    x="value",
    y="Count",
    col="comparison_var",
    hue="Contributor Type",
    hue_order=[
        "NCC-A",
        "CC-A",
        "CC-NA",
    ],
    palette=cmaps.bold[3:]._colors.tolist(),
    kind="line",
    estimator="mean",
    legend=True,
    facet_kws={"sharex": False, "sharey": False},
    height=3.5,
)

# Iter over axes and set x labels
for i, ax in enumerate(g.axes.flat):
    if i == 0:
        ax.set_title("A")
        ax.set_xlabel("Publication Year")
    else:
        ax.set_title("B")
        ax.set_xlabel("Total Authors")
        ax.set_ylabel("Count")

# Move legend to below the plot
sns.move_legend(
    g,
    bbox_to_anchor=(0.4, -0.0001),
    loc="upper center",
    ncol=3,
    fontsize=10,
    title_fontsize=12,
)

# Add some space between plots
g.fig.subplots_adjust(wspace=0.4)
```

### Modeling Article Citations

Building upon previous work examining the effects of team size and team diversity on scientific impact and software quality (see @sec-background), we investigate how the number of code contributors within a research team may be associated with an article's research impact. We hypothesized that more code contributors might signal greater technical complexity in research, which may be associated with higher citation counts as the community builds upon more technically sophisticated works (*H1*). Using our filtered dataset of article-repository pairs (with detailed counts reported in Table S4), we conducted multiple generalized linear regression analyses to examine these relationships while controlling for various factors. Each generalized linear regression model included controls for the total number of authors listed on the publication and the number of years since the date of publication (as a decimal). Without additional controls for domain, open access status, or article type (full model outputs in Table S9 through Table S12), our analysis revealed a modest positive association between the number of code-contributing authors and article citations, with each code-contributing author associated with, on average, a \~4.2% increase in article citations (p \< 0.001).

When controlling for article type (Table S12), we observed divergent patterns between preprints and research articles. For preprints, each code-contributing non-author was associated with a statistically significant \~3.0% decrease in citations (p \< 0.005). In contrast, research articles showed more positive associations: we found a significant positive relationship between code-contributing authors and citations (p \< 0.001), though we cannot estimate the precise magnitude due to the non-significant main effect in the model. Additionally, each code-contributing non-author was associated with a \~0.1% increase in expected citations for research articles (p \< 0.001).

Based on these findings, we **fail to reject** our hypothesis (*H1*) that "the number of individuals contributing code to a publication's associated repository positively correlates with the article's citation count." It is important to note that, the relationship between contributors and citations is statistically significant, but these effects are modest in magnitude, and differ substantially between research articles (positive association) and preprints (negative association for non-author code contributors). These variations suggest that the relationship between code contributions and citation impact is context-dependent and more complex than we originally stated in our hypothesis. We return to this finding in the discussion and limitations sections that follow.

```{python}
def compute_article_level_models(
    y_col: str,
    data: pd.DataFrame,
    glm_family: sm.families.Family,
) -> dict[str, sm.GLM]:
    # Remove outliers
    no_outliers = data[
        data[y_col].between(
            data[y_col].quantile(0.03),
            data[y_col].quantile(0.97),
        )
    ].copy()

    # Remove nans
    no_outliers = no_outliers.dropna(subset=[y_col])

    # Replace names
    no_outliers = no_outliers.rename(
        columns={
            "n_authors": "Total Authors",
            # "n_author_non_devs": "Non-Code-Contrib. Authors",
            "n_author_devs": "Code-Contrib. Authors",
            "n_non_author_devs": "Code-Contrib. Non-Authors",
        }
    )

    # Replace other names (except const.) by removing `_` and title casing
    no_outliers = no_outliers.rename(
        columns=lambda x: x.replace("_", " ").title() if x not in ["const", y_col] else x
    )

    # Common features to use in all models
    required_features = [
        y_col,
        "Total Authors",
        # "n_author_non_devs",
        "Code-Contrib. Authors",
        "Code-Contrib. Non-Authors",
        "Years Since Publication",
    ]

    

    # Iter over different control variables and create models for each
    models = {}
    for control_var in [
        "no-control",
        "Article Type",
        "Domain",
        "Is Open Access",
    ]:
        if control_var != "no-control":
            # Get control variable list
            control_variables = [
                col for col in no_outliers.columns if col.startswith(control_var)
            ]

            # Create control variable subset of the data
            control_var_subset = no_outliers[required_features + control_variables].copy()

            # Create interactions
            for coding_status_col in ["Code-Contrib. Authors", "Code-Contrib. Non-Authors"]:
                for control_col in control_variables:
                    control_var_subset[f"{coding_status_col} × {control_col}"] = (
                        control_var_subset[coding_status_col]
                        * control_var_subset[control_col]
                    )
        else:
            control_var_subset = no_outliers[required_features].copy()

        # Drop inf and nan
        control_var_subset = control_var_subset.replace(
            [float("inf"), -float("inf")], float("nan")
        ).dropna()

        # Create x and y
        y = control_var_subset[y_col]
        x = control_var_subset.drop(columns=[y_col])
        x = sm.add_constant(x)

        # Fit model
        model = sm.GLM(y, x, family=glm_family).fit()
        models[control_var] = model

    return models
```

```{python}
# LaTeX templates
model_results_row_template = """    {bold_str}\\cellcolor{{{color}}}{var_name}{stars} & {bold_str}\\cellcolor{{{color}}}{coef:.2f} & {bold_str}\\cellcolor{{{color}}}{p:.2f} & {bold_str}\\cellcolor{{{color}}}{ci_low:.2f} & {bold_str}\\cellcolor{{{color}}}{ci_high:.2f} \\\\"""

# Table header and footer templates
model_results_table_header = """\\begin{tabular}{l*{6}{r}}
\\toprule
\\textbf{Variable} & \\textbf{coef} & \\textbf{P>|z|} & \\multicolumn{2}{c}{\\textbf{[0.025 0.975]}} \\\\
\\midrule"""

model_results_table_footer = """\\bottomrule
\\end{tabular}"""

def convert_model_results_to_printable_pdf_ready(
    model: sm.GLM,
    tbl_cap: str,
    tbl_label: str,
) -> tuple[str, pd.DataFrame]:
    # Get only the dataframe
    summary_simple_tab = model.summary().tables[1]
    model_results_df = pd.read_html(StringIO(summary_simple_tab.as_html()), header=0, index_col=0)[0]

    # Add exponentiated coef
    model_results_df["exp(coef)"] = np.exp(model_results_df["coef"])

    # Keep only the specified columns
    model_results_df = model_results_df[
        ["exp(coef)", "coef", "z", "P>|z|", "[0.025", "0.975]"]
    ]

    # Set index name to "variable"
    model_results_df.index.name = "variable"
    model_results_df = model_results_df.reset_index()

    rows_latex = []
    for i, result_row in model_results_df.iterrows():
        # Determine if row should be bold and if stars should be added
        is_significant = result_row["P>|z|"] < 0.05
        stars = ""
        if result_row["P>|z|"] < 0.001:
            stars = "~$^{***}$"
        elif result_row["P>|z|"] < 0.01:
            stars = "~$^{**}$"
        elif result_row["P>|z|"] < 0.05:
            stars = "~$^{*}$"
        
        
        
        # Handle bolding - only for significant rows
        if is_significant:
            bold_str = "\\bfseries"
        else:
            bold_str = ""
        
        # Set background color for alternating rows
        color = "gray!10" if i % 2 == 1 else "white"
        
        # Format the row
        rows_latex.append(
            model_results_row_template.format(
                bold_str=bold_str,
                var_name=result_row["variable"].replace("_", " "),
                # exp_coef=result_row["exp(coef)"],
                coef=result_row["coef"],
                # z=result_row["z"],
                p=result_row["P>|z|"],
                ci_low=result_row["[0.025"],
                ci_high=result_row["0.975]"],
                stars=stars,
                color=color
            )
        )

    # Combine all parts
    regression_table_latex = f"""\\begin{{table}}
\\centering
\\caption{{{tbl_cap}}}
\\label{{{tbl_label}}}
{model_results_table_header}
{chr(10).join(rows_latex)}
{model_results_table_footer}
\\end{{table}}"""

    return regression_table_latex, model_results_df
```

```{python}
# Create models for cited_by_count
article_cited_by_count_models = compute_article_level_models(
    "cited_by_count",
    team_comp_no_push_after_pub_dummies,
    glm_family=sm.families.NegativeBinomial(),
)
```

## Characteristics of Scientific Code Contributors

### Author Positions of Code Contributing Authors

```{python}
def _run_posthocs(
    data: pd.DataFrame,
    split_var: str,
) -> list[dict[str, str]]:
    # Conduct pairwise posthocs
    binom_results = []
    for split_val in data[split_var].unique():
        split_val_subset = data.loc[
            data[split_var] == split_val
        ]

        # Run test
        results = binomtest(
            sum(split_val_subset["is_code_contributor"]),
            len(split_val_subset),
            0.5,
        )
        
        # Conduct binomial test
        binom_results.append(
            {
                split_var: split_val,
                "p": results.pvalue,
                "statistic": results.statistic,
                "n": len(split_val_subset),
                "n_code_contributors": sum(split_val_subset["is_code_contributor"]),
            }
        )

        # P adjust
        _, p_values, _, _ = multipletests(
            [result["p"] for result in binom_results],
            method="bonferroni",
        )

        # Replace p values
        for i, result in enumerate(binom_results):
            result["p"] = p_values[i]
        
    # Print results
    formatted_binom_results = []
    for result in binom_results:
        formatted_binom_results.append({
            split_var.replace("_", " ").title(): result[split_var].title(),
            "Coding": result["n_code_contributors"],
            "Total": result["n"],
            "p": result["p"],
        })

    return formatted_binom_results
    

def _run_chi2_and_posthocs(
    data: pd.DataFrame,
    control_var: str | None,
    split_var: str,
) -> list[dict[str, str | float | int]]:
    chi2_result_str_template = "χ2={stat:.1f}, p={p:.3f}, n={n}"
    
    return_vals = []

    if control_var is None:
        xtabs = pd.crosstab(
            data[split_var],
            data["is_code_contributor"],
        )
        chi2_result = chi2_contingency(xtabs)
        if chi2_result.pvalue < 0.05:
            posthoc_results = _run_posthocs(
                data,
                split_var=split_var,
            )

            for posthoc_result in posthoc_results:
                return_vals.append({
                    "Control": "Overall",
                    "Subset": "Overall",
                    **posthoc_result,
                })

        else:
            pass
    else:
        for control_val in data[control_var].unique():
            # Get data with control_val subset
            control_val_subset = data.loc[
                data[control_var] == control_val
            ]
            xtabs = pd.crosstab(
                control_val_subset[split_var],
                control_val_subset["is_code_contributor"],
            )
            chi2_result = chi2_contingency(xtabs)
            posthoc_results = _run_posthocs(
                control_val_subset,
                split_var=split_var,
            )

            for posthoc_result in posthoc_results:
                return_vals.append({
                    "Control": control_var.replace("_", " ").title(),
                    "Subset": control_val.replace("_", " ").title(),
                    **posthoc_result,
                })

    return return_vals
```

```{python}
doc_contribs_for_code_char = document_contributors.loc[
    document_contributors["document_id"].isin(team_comp_no_push_after_pub["document_id"])
].merge(
    team_comp_no_push_after_pub[[
        "document_id",
        "repository_id",
        "is_open_access",
        "domain",
        "article_type",
    ]]
)

# Iter over rows and check if the author is a dev on the same article-repo pair
doc_contribs_for_code_char_rows = []
for i, row in doc_contribs_for_code_char.iterrows():
    # Get devs
    this_repo_devs = repository_contributors.loc[
        repository_contributors["repository_id"] == row["repository_id"]
    ]

    # Get the set of researcher_dev_links for the authors
    author_dev_links = researcher_dev_links.loc[
        researcher_dev_links["researcher_id"] == row.researcher_id
    ].sort_values("predictive_model_confidence", ascending=False)

    # Drop duplicates by developer_account_id (keeping first)
    # as we may have accidently matched the same dev to the multiple authors
    author_dev_links = author_dev_links.drop_duplicates(
        subset=["developer_account_id"],
        keep="first",
    )

    # Drop any author dev links that have less than 97% confidence
    author_dev_links = author_dev_links.loc[
        author_dev_links["predictive_model_confidence"] >= 0.97
    ]

    # If no author dev links return same rows and "is_code_contributor" as False
    if len(author_dev_links) == 0:
        doc_contribs_for_code_char_rows.append(
            {
                **row.to_dict(),
                "is_code_contributor": False,
            }
        )

    # If there are more than three author dev links, ignore
    elif len(author_dev_links) > 3:
        continue
    
    else:
        # Add same rows and add "is_code_contributor" based on if developer_account_id is in this_repo_devs
        doc_contribs_for_code_char_rows.append(
            {
                **row.to_dict(),
                "is_code_contributor": any(
                    author_dev_link["developer_account_id"]
                    in this_repo_devs["developer_account_id"].unique()
                    for _, author_dev_link in author_dev_links.iterrows()
                ),
            }
        )

# Create dataframe
doc_contribs_for_code_char = pd.DataFrame(doc_contribs_for_code_char_rows)

# Replace binary values in "is_open_access" to "Open Access" and "Closed Access"
doc_contribs_for_code_char["is_open_access"] = (
    doc_contribs_for_code_char.apply(
        lambda x: "Open Access" if x["is_open_access"] == 1 else "Closed Access",
        axis=1,
    )
)

# Replace binary values in "is_corresponding" to "Corresponding" and "Not Corresponding"
doc_contribs_for_code_char["is_corresponding"] = (
    doc_contribs_for_code_char.apply(
        lambda x: "Corresponding" if x["is_corresponding"] == 1 else "Not Corresponding",
        axis=1,
    )
)

# Calculate the percent of first authors who are code contributors
first_author_code_contributors = doc_contribs_for_code_char.loc[
    doc_contribs_for_code_char["position"] == "first"
]["is_code_contributor"].sum()
percent_first_authors_code_contributors = (
    first_author_code_contributors
    / len(
        doc_contribs_for_code_char.loc[
            doc_contribs_for_code_char["position"] == "first"
        ]
    )
)
percent_first_authors_code_contributors_str = f"{percent_first_authors_code_contributors:.1%}"

middle_author_code_contributors = doc_contribs_for_code_char.loc[
    doc_contribs_for_code_char["position"] == "middle"
]["is_code_contributor"].sum()
percent_middle_authors_code_contributors = (
    middle_author_code_contributors
    / len(
        doc_contribs_for_code_char.loc[
            doc_contribs_for_code_char["position"] == "middle"
        ]
    )
)
percent_middle_authors_code_contributors_str = f"{percent_middle_authors_code_contributors:.1%}"

last_author_code_contributors = doc_contribs_for_code_char.loc[
    doc_contribs_for_code_char["position"] == "last"
]["is_code_contributor"].sum()
percent_last_authors_code_contributors = (
    last_author_code_contributors
    / len(
        doc_contribs_for_code_char.loc[
            doc_contribs_for_code_char["position"] == "last"
        ]
    )
)
percent_last_authors_code_contributors_str = f"{percent_last_authors_code_contributors:.1%}"

domain_code_char = pd.DataFrame(
    _run_chi2_and_posthocs(
        doc_contribs_for_code_char,
        control_var="domain",
        split_var="position",
    )
)
position_sorter = ["First", "Middle", "Last"]
domain_code_char["Position"] = pd.Categorical(
    domain_code_char["Position"],
    categories=position_sorter,
    ordered=True,
)
domain_code_char = domain_code_char.sort_values(["Subset", "Position"])

article_type_code_char = pd.DataFrame(
    _run_chi2_and_posthocs(
        doc_contribs_for_code_char,
        control_var="article_type",
        split_var="position",
    )
)
article_type_code_char["Position"] = pd.Categorical(
    article_type_code_char["Position"],
    categories=position_sorter,
    ordered=True,
)
article_type_code_char = article_type_code_char.sort_values(["Subset", "Position"])

open_access_status_code_char = pd.DataFrame(
    _run_chi2_and_posthocs(
        doc_contribs_for_code_char,
        control_var="is_open_access",
        split_var="position",
    )
)
open_access_status_code_char["Position"] = pd.Categorical(
    open_access_status_code_char["Position"],
    categories=position_sorter,
    ordered=True,
)
open_access_status_code_char = open_access_status_code_char.sort_values(["Subset", "Position"])

# Run chi2 and posthocs for overall author position
overall_code_char = pd.DataFrame(
    _run_chi2_and_posthocs(
        doc_contribs_for_code_char,
        control_var=None,
        split_var="position",
    )
)
overall_code_char["Position"] = pd.Categorical(
    overall_code_char["Position"],
    categories=position_sorter,
    ordered=True,
)
overall_code_char = overall_code_char.sort_values(["Subset", "Position"])
```

Building upon previous work examining the relationship between authorship position and research contributions, we investigate how author position may relate to code contribution patterns. We hypothesized that first authors, traditionally contributing the bulk of intellectual and experimental work, are most likely to contribute code to a project (*H2a*). 

To analyze these patterns within our previously filtered dataset of article-repository pairs (Table S4), we conducted Chi-square tests of independence between author position and code contribution status. These tests revealed significant associations between author position and likelihood of code contribution overall and when controlling for research domain, article type, and open access status (all p \< 0.01), indicating that the proportion of authors contributing code differs significantly based on author position[^11]. Following these significant associations, we examined the specific proportions across positions (detailed post-hoc test outputs are in Table S13): `{python} percent_first_authors_code_contributors_str` of first authors contributed code to their projects, compared to only `{python} percent_middle_authors_code_contributors_str` of middle authors and `{python} percent_last_authors_code_contributors_str` of last authors. The differences in these proportions remained statistically significant across all tested scenarios, regardless of research domain, article type, or open access status.

[^11]: Community practices and norms around authorship order vary across disciplines and over time. One particular changing practice is the adoption of shared first authorship, where two or more authors are designated as having contributed equally to the work. However, after all filtering required for analysis was complete, none of the remaining articles included multiple first authors.

Based on these findings, we ***fail to reject*** our hypothesis (*H2a*) that "first authors have higher code contribution rates than authors in other positions." The data demonstrates that the proportion of first authors who contribute code (`{python} percent_first_authors_code_contributors_str`) is significantly higher than the proportion of both middle authors (`{python} percent_middle_authors_code_contributors_str`) and last authors (`{python} percent_last_authors_code_contributors_str`). This relationship remains robust and statistically significant across all tested conditions, including variations in research domain, article type, and open access status, indicating a fundamental connection between authorship position and technical contribution in scientific research.

### Corresponding Status of Code Contributing Authors

```{python}
# Run chi2 and posthocs for overall corresponding status
domain_code_corresponding = pd.DataFrame(
    _run_chi2_and_posthocs(
        doc_contribs_for_code_char,
        control_var="domain",
        split_var="is_corresponding",
    )
).sort_values(["Subset", "Is Corresponding"])

article_type_code_corresponding = pd.DataFrame(
    _run_chi2_and_posthocs(
        doc_contribs_for_code_char,
        control_var="article_type",
        split_var="is_corresponding",
    )
).sort_values(["Subset", "Is Corresponding"])

open_access_status_code_corresponding = pd.DataFrame(
    _run_chi2_and_posthocs(
        doc_contribs_for_code_char,
        control_var="is_open_access",
        split_var="is_corresponding",
    )
).sort_values(["Subset", "Is Corresponding"])

overall_code_corresponding = pd.DataFrame(
    _run_chi2_and_posthocs(
        doc_contribs_for_code_char,
        control_var=None,
        split_var="is_corresponding",
    )
).sort_values(["Subset", "Is Corresponding"])

# Calculate the percent of corresponding authors who are code contributors
corres_author_code_contributors = doc_contribs_for_code_char.loc[
    doc_contribs_for_code_char["is_corresponding"] == "Corresponding"
]["is_code_contributor"].sum()
percent_corresponding_authors_code_contributors = (
    corres_author_code_contributors
    / len(
        doc_contribs_for_code_char.loc[
            doc_contribs_for_code_char["is_corresponding"] == "Corresponding"
        ]
    )
)
percent_corresponding_authors_code_contributors_str = f"{percent_corresponding_authors_code_contributors:.1%}"

non_corres_author_code_contributors = doc_contribs_for_code_char.loc[
    doc_contribs_for_code_char["is_corresponding"] == "Not Corresponding"
]["is_code_contributor"].sum()
percent_non_corresponding_authors_code_contributors = (
    non_corres_author_code_contributors
    / len(
        doc_contribs_for_code_char.loc[
            doc_contribs_for_code_char["is_corresponding"] == "Not Corresponding"
        ]
    )
)
percent_non_corresponding_authors_code_contributors_str = f"{percent_non_corresponding_authors_code_contributors:.1%}"
```

Building upon our analysis of author position, we next examine how corresponding author status relates to code contribution patterns. We hypothesized that corresponding authors, who traditionally maintain research artifacts and serve as primary points of contact, would be more likely to contribute code compared to non-corresponding authors (*H2b*)

To analyze these relationships within our filtered dataset of article-repository pairs, we conducted Chi-square tests of independence between corresponding author status and code contribution status. Our analysis revealed patterns contrary to our initial hypothesis. The proportion of code contributors was low among both groups, with only `{python} percent_corresponding_authors_code_contributors_str` of corresponding authors and `{python} percent_non_corresponding_authors_code_contributors_str` of non-corresponding authors contributing code to their projects. Further examination (full post-hoc outputs in Table S14) showed that this pattern holds across nearly all conditions, with only one exception: corresponding authors in closed-access publications showed no significant difference in their proportion of code contributors. However, this was tested with a sample of less than 200 authors.

Based on these findings, we ***reject*** our hypothesis (*H2b*) that "corresponding authors have higher code contribution rates than non-corresponding authors." Contrary to our expectations, our analysis revealed that the proportion of code contributors among corresponding authors (`{python} percent_corresponding_authors_code_contributors_str`) did not significantly differ from the proportion among non-corresponding authors (`{python} percent_non_corresponding_authors_code_contributors_str`). This pattern of similar proportions remained consistent across most studied conditions, with a single exception in closed-access publications which we believe is due to the relatively small sample size available for testing (n=194).

### Modeling Author H-Index

```{python}
# First, get the set of researchers who have at least 3 documents
researchers_w_3_docs = researchers.loc[
    researchers["id"].isin(
        document_contributors["researcher_id"]
        .value_counts()
        .loc[lambda x: x >= 3]
        .index
    )
]

# Use sample?
if USE_SAMPLE:
    researchers_w_3_docs = researchers_w_3_docs.sample(frac=0.02, random_state=12)

# Next, for each researcher, get the set of documents they have contributed to
researchers_w_3_docs = document_contributors.loc[
    document_contributors["researcher_id"].isin(researchers_w_3_docs["id"])
].merge(
    researchers_w_3_docs,
    left_on="researcher_id",
    right_on="id",
)

# Attach document for publication date
researchers_w_3_docs = researchers_w_3_docs.merge(
    documents[["id", "publication_date"]],
    left_on="document_id",
    right_on="id",
).drop(
    columns=["id"],
)

# Keep only certain columns
researchers_w_3_docs = researchers_w_3_docs[
    [
        "researcher_id",
        "document_id",
        "publication_date",
        "position",
        "is_corresponding",
        "works_count",
        "cited_by_count",
        "h_index",
        "i10_index",
        "two_year_mean_citedness",
    ]
]

# Next, for each researcher_doc, attach the document details (domain, reduced_doc_type)
researchers_w_3_docs = (
    researchers_w_3_docs.merge(
        document_topics[["document_id", "topic_id"]],
        left_on="document_id",
        right_on="document_id",
    )
    .merge(
        topics[["id", "domain_name"]],
        left_on="topic_id",
        right_on="id",
    )
    .drop(
        columns=["id", "topic_id"],
    )
    .merge(
        reduced_doc_types,
        left_on="document_id",
        right_on="document_id",
    )
)

# Now for each of these, we want to see if they have coded on the document
researchers_coded = []
individuals_removed_from_confidence_thresh = 0
for _, row in researchers_w_3_docs.iterrows():
    # Check for dev account
    dev_links = researcher_dev_links.loc[
        researcher_dev_links["researcher_id"] == row["researcher_id"]
    ]

    # Remove any links with less than 97% confidence
    before_drop_count = len(dev_links)
    dev_links = dev_links.loc[
        dev_links["predictive_model_confidence"] >= 0.97
    ]
    after_drop_count = len(dev_links)
    individuals_removed_from_confidence_thresh += (
        before_drop_count - after_drop_count
    )

    # Fast exit
    if len(dev_links) == 0:
        researchers_coded.append(
            {
                "researcher_id": row["researcher_id"],
                "document_id": row["document_id"],
                "coded_on_article": 0,
            }
        )
        continue

    # Skip this person if they have more than 3 links
    # Likely something went wrong
    if len(dev_links) > 3:
        continue

    # Get repos associated with document
    repo_links_for_doc = doc_repo_links.loc[
        doc_repo_links["document_id"] == row["document_id"]
    ]

    # Skip if there is more than 1 repo associated with the document
    # We just don't know how to handle these cases right now
    if len(repo_links_for_doc) > 1:
        continue

    # Also skip if 0
    if len(repo_links_for_doc) == 0:
        continue

    # Get the repo_id for the single repo
    repo_id = repo_links_for_doc["repository_id"].iloc[0]

    # Get the repo_contributors for this repository
    repo_contributors = repository_contributors.loc[
        repository_contributors["repository_id"] == repo_id
    ]

    # Check if any of the dev accounts are in the repo contribs
    researcher_coded = (
        len(
            set(repo_contributors["developer_account_id"].unique()).intersection(
                set(dev_links["developer_account_id"].unique()),
            )
        )
        > 0
    )

    # Finally assert any of the repo_contributors are the dev account
    # associated with the researcher
    researchers_coded.append(
        {
            "researcher_id": row["researcher_id"],
            "document_id": row["document_id"],
            "coded_on_article": int(researcher_coded),
        }
    )

# Create dataframe
researchers_coded_df = pd.DataFrame(researchers_coded)

# Merge with researchers_w_3_docs
researchers_w_3_docs_and_coded = researchers_coded_df.merge(
    researchers_w_3_docs,
    left_on=["researcher_id", "document_id"],
    right_on=["researcher_id", "document_id"],
)

def _mode_or_recent_reduce(group: pd.DataFrame, col: str) -> str:
    # Get the mode
    mode = group[col].mode().tolist()
    if len(mode) == 1:
        return mode[0]

    # Otherwise, iter over most recent publications until value in mode is found
    group_ordered_by_date = group.sort_values("publication_date", ascending=False)
    for _, row in group_ordered_by_date.iterrows():
        if row[col] in mode:
            return row[col]


def _agg_apply(group: pd.DataFrame) -> dict:
    return {
        "n_documents": group["document_id"].nunique(),
        "n_coded": group["coded_on_article"].sum(),
        "works_count": group["works_count"].iloc[0],
        "cited_by_count": group["cited_by_count"].iloc[0],
        "h_index": group["h_index"].iloc[0],
        "i10_index": group["i10_index"].iloc[0],
        "two_year_mean_citedness": group["two_year_mean_citedness"].iloc[0],
        "position": _mode_or_recent_reduce(group, "position"),
        "domain_name": _mode_or_recent_reduce(group, "domain_name"),
        "reduced_doc_type": _mode_or_recent_reduce(group, "reduced_doc_type"),
    }


researchers_w_3_docs_and_coded_agg = (
    researchers_w_3_docs_and_coded.groupby("researcher_id")[
        [col for col in researchers_w_3_docs_and_coded if col != "researcher_id"]
    ]
    .apply(_agg_apply)
    .reset_index(name="dicts")
)
researchers_w_3_docs_and_coded_agg = researchers_w_3_docs_and_coded_agg.join(
    pd.json_normalize(researchers_w_3_docs_and_coded_agg["dicts"])
).drop(columns=["dicts"])

# Create three features for coding status
# "any" coding status
# "majority" coding status
# "always" coding status
# determine type by taking the percentage of documents coded on
# and determining if it is greater than 0, greater than 0.5, or 1
researchers_w_3_docs_and_coded_agg["coding_pct"] = (
    researchers_w_3_docs_and_coded_agg["n_coded"]
    / researchers_w_3_docs_and_coded_agg["n_documents"]
)

researchers_w_3_docs_and_coded_agg["any_coding"] = (
    (researchers_w_3_docs_and_coded_agg["coding_pct"] > 0)
    & (researchers_w_3_docs_and_coded_agg["coding_pct"] <= 0.5)
).astype(int)
researchers_w_3_docs_and_coded_agg["majority_coding"] = (
    (researchers_w_3_docs_and_coded_agg["coding_pct"] > 0.5)
    & (researchers_w_3_docs_and_coded_agg["coding_pct"] < 1)
).astype(int)
researchers_w_3_docs_and_coded_agg["always_coding"] = (
    researchers_w_3_docs_and_coded_agg["coding_pct"] == 1
).astype(int)

# Drop n_documents, n_coded and
# rename "position" to "common_author_position",
# "domain_name" to "common_domain",
# and "reduced_doc_type" to "common_article_type"
researchers_w_3_docs_and_coded_agg = researchers_w_3_docs_and_coded_agg.drop(
    columns=["n_documents", "n_coded"]
)
researchers_w_3_docs_and_coded_agg = researchers_w_3_docs_and_coded_agg.rename(
    columns={
        "position": "common_author_position",
        "domain_name": "common_domain",
        "reduced_doc_type": "common_article_type",
    }
)

# Get dummies for categorical variables
researchers_w_3_docs_and_coded_agg_dummies = pd.get_dummies(
    researchers_w_3_docs_and_coded_agg,
    columns=["common_author_position", "common_domain", "common_article_type"],
    drop_first=True,
)

# Cast all to float
researchers_w_3_docs_and_coded_agg_dummies = (
    researchers_w_3_docs_and_coded_agg_dummies.astype(float)
)
```

Building upon previous work examining career implications for researchers who prioritize software development (see @sec-background), we investigated how varying levels of code contribution relate to scholarly impact through h-index metrics. To ensure a robust analysis, we applied several key data filtering steps. We only included researchers with at least three publications in our dataset, removed those with more than three developer account associations, and used each researcher's most common domain, article type, and author position, with ties broken by the most recent occurrence. We removed h-index outliers by excluding researchers below the bottom 3rd and above the top 97th percentiles. Finally, we removed any author-developer-account pairs with predictive model confidence of less than 0.97. Counts for researchers in each coding frequency group are provided in Table S15.

We categorized researchers' coding contributions into mutually exclusive groups: non-coders (no code contributions), any coding (code contribution in less than half of article-repository pairs), majority coding (code contribution in at least half, but not all, article-repository pairs), and always coding (code contribution in every article-repository pair).

@fig-author-h-index-by-coding-status shows the distribution of author h-indices across these coding frequency groups, grouped by author position, publication type, and research domain.

```{python}
#| label: fig-author-h-index-by-coding-status
#| fig-cap: "Distribution of author h-index by coding frequency across three key publication factors. Results are grouped by each author's most frequent: (1) position in publication bylines (first, middle, or last), (2) publication type (preprint, research article, or software article), and (3) research domain (Social Sciences, Physical Sciences, Health Sciences, or Life Sciences). Within each subplot, h-indices are divided by the author's coding frequency: 'none' (no coding in any of their publications), 'any' (coding in at least one but fewer than half of their publications), 'majority' (coding in at least half but not all of their publications), and 'always' (coding in each of their publications). Authors are only included if they have three or more publications within our dataset and are associated with no more than three developer accounts, with each association having a predicted model confidence of at least 97%."

def _get_coding_status_string(row: pd.Series) -> str:
    if row["any_coding"] == 1:
        return "any"
    elif row["majority_coding"] == 1:
        return "majority"
    elif row["always_coding"] == 1:
        return "always"
    else:
        return "none"

researchers_w_3_docs_and_coded_agg["coding_status"] = researchers_w_3_docs_and_coded_agg.apply(
    _get_coding_status_string,
    axis=1,
)

# Select columns of interest
researchers_w_3_docs_and_coded_agg_subset_for_vis = researchers_w_3_docs_and_coded_agg[
    [
        "researcher_id",
        "h_index",
        "coding_status",
        "common_author_position",
        "common_domain",
        "common_article_type",
    ]
]

# Melt control variables
researchers_w_3_docs_and_coded_agg_vis_melted = researchers_w_3_docs_and_coded_agg_subset_for_vis.melt(
    id_vars=["researcher_id", "h_index", "coding_status"],
    value_vars=[
        "common_author_position",
        "common_domain",
        "common_article_type",
    ],
    var_name="control_var",
    value_name="control_value",
)

# Define visualization order and control variables
vis_order = ["none", "any", "majority", "always"]
control_vars = OrderedDict([
    ("common_author_position", ["first", "middle", "last"]),
    ("common_article_type", ["preprint", "research article", "software article"]),
    ("common_domain", ["Social Sciences", "Physical Sciences", "Health Sciences", "Life Sciences"]),
])

# Set up the figure with appropriate size
fig = plt.figure(figsize=(8, 9))

# Calculate grid dimensions based on control variables
num_controls = len(control_vars)
max_subsets = max(len(values) for values in control_vars.values())
grid_height = num_controls * 3  # 3 rows per control variable

# Iterate through control variables to create subplots
for control_idx, (control_var, control_values) in enumerate(control_vars.items()):
    # Determine row position for this control variable
    row_pos = control_idx * 3
    
    # Create subplots for each control value
    for col_idx, control_value in enumerate(control_values):
        # Create the subplot
        ax = plt.subplot2grid(
            (grid_height, max_subsets),
            (row_pos, col_idx),
            rowspan=2,
            colspan=1
        )
        
        # Filter data for this control variable and value
        subset_data = researchers_w_3_docs_and_coded_agg_vis_melted[
            (researchers_w_3_docs_and_coded_agg_vis_melted["control_var"] == control_var) & 
            (researchers_w_3_docs_and_coded_agg_vis_melted["control_value"] == control_value)
        ]
        
        # Create boxplot with specified configuration
        sns.boxplot(
            data=subset_data,
            x="coding_status",
            y="h_index",
            hue="coding_status",
            hue_order=vis_order,
            order=vis_order,
            ax=ax,
            showfliers=False,
            legend=False,
        )

        # Set ylim to row specific values
        ax.set_ylim([-1, 115])
        
        # Set titles and labels
        ax.set_title(f"{control_value.title()}", fontsize=14)
        
        if col_idx == 0:
            ax.set_ylabel("h-index", fontsize=14)
        else:
            ax.set_ylabel("")
            
        # Never show xlabel as we use legend
        # if col_idx == 0:
        #     ax.set_xlabel("Coding Frequency", loc="left", fontproperties={"size": 16, "weight": "bold"})
        # else:
        ax.set_xlabel("")
            
        # Rotate x-tick labels for better readability
        plt.setp(ax.get_xticklabels(), rotation=45, ha="right")

    # Add row header for this control variable
    fig.text(
        0.13, 
        0.95 - (control_idx * 0.299), 
        f"{control_var.replace('_', ' ').title().replace("Common", "").strip()}", 
        fontsize=16, 
        ha="left", 
        va="center", 
        fontweight="bold"
    )


# # Add a legend outside the plots
# handles = [plt.Rectangle((0,0), 1, 1, color=tuple(cmaps.bold[2:]._colors.tolist()[i])) for i in range(len(vis_order))]
# legend = fig.legend(
#     handles, 
#     vis_order, 
#     bbox_to_anchor=(0.92, 0.52),  # Position at bottom center
#     fontsize=16,
#     title="Author Coding Frequency",
#     title_fontproperties={"size": 16, "weight": "bold"},
#     alignment="left",
# )

# Adjust layout
plt.subplots_adjust(hspace=0.2, wspace=0.2, bottom=0.1)
plt.tight_layout(rect=[0.03, 0.06, 0.97, 0.95])

# Draw a horizontal lines at those coordinates
for y in [0.69, 0.39]:
    line = plt.Line2D([0.066, 0.944], [y,y], transform=fig.transFigure, color="black", linestyle="--")
    fig.add_artist(line)

# Show plot
plt.show()
```

Using multiple generalized linear regressions, and while controlling for an author's total number of published works, we find a consistent and statistically significant negative relationship between code contribution frequency and h-index across multiple controls. Our initial analysis, controlled only by an author's publication count (Table S16), indicates increasingly adverse h-index effects as researcher coding frequency increases. Compared to non-coding authors, researchers were associated with progressively lower h-indices: authors who occasionally provided code showed a \~27.3% lower h-index (p \< 0.001), authors who provided code for a majority of their works demonstrated a \~53.5% lower h-index (p \< 0.001), and always coding authors exhibited a \~62.1% lower h-index (p \< 0.001).

When controlling for author position (Table S17), we found a general pattern of reduced h-indices with increased code contribution, with one notable exception. Occasional coding first authors were associated with a \~14.9% higher h-index (p \< 0.001), while always coding first authors saw a \~21.6% reduction compared to non-coding first authors (p \< 0.001). For middle and last authors, the pattern was more consistently negative. Middle authors who occasionally coded showed a \~26.6% lower h-index (p \< 0.001), and those who always coded demonstrated a \~52.9% lower h-index (p \< 0.001). Similarly, last authors who occasionally coded experienced a \~13.1% lower h-index (p \< 0.001), with always coding last authors showing a \~45.7% lower h-index (p \< 0.001).

When controlling for research domain (Table S18), majority coding scientists showed significant h-index reductions across all domains. Health sciences researchers saw the most dramatic reduction at \~76.5% (p \< 0.001), followed by physical sciences at \~52.6% (p \< 0.001), social sciences at \~51.4% (p \< 0.001), and life sciences at \~47.1% (p \< 0.001).

Analyzing by common article type (Table S19) revealed similar patterns. For authors primarily publishing preprints, the h-index reductions were substantial: \~25.6% for occasional coding, \~53.5% for majority coding, and \~62.9% for always coding authors. Authors primarily publishing software articles showed slightly better but still significant reductions: \~33.1% for majority coding and \~33.0% for always coding authors.

Based on these findings, we ***fail to reject*** our hypothesis (*H3*) that "the frequency with which individual researchers contribute code to their research projects is negatively correlated with their h-index." Our analysis demonstrates a clear and statistically significant negative relationship between code contribution frequency and scholarly impact as measured by the researcher's h-index. This relationship was robust across multiple analytical controls, including author position, research domain, and article type. These results are particularly striking because our models include publication count as an input feature, suggesting that these h-index reductions persist even when accounting for total research output.

# Discussion {#sec-discussion}

Our analysis reveals significant disparities in the recognition of software contributions to scientific research, with \~28.6% (n=5,694) of articles having code-contributors not matched to any article author, partially representing unrecognized code contribution. This persistent pattern over time and team size suggests a systemic disconnect between software development and scientific recognition systems, reflecting challenges in how scientific contributions are valued and credited. This exclusion reflects what @shapin1989invisible observed about scientific authority—the selective attribution of technical work as either genuine knowledge or mere skill significantly impacts who receives formal recognition. These findings further support previous surveys @olivier_philippe_2019_2585783 and @Carver2022ASO where scientists report the relegation of software contributors to either acknowledgment sections or receiving no credit at all. The stability of this pattern over time indicates that this phenomenon has embedded itself in scientific software development rather than representing a transitional phase, raising questions about scientific labor and how reward structures integrate technical contributions.

Our finding that, on average, article-repository pairs have only a single code contributor mirrors prior work from @farber2020analyzingGithubPapers. Further, the distribution of code contributions across author positions provides context to the hierarchical organization of scientific work. First authors are significantly more likely to contribute code with `{python} percent_first_authors_code_contributors_str` of all first authors in our dataset contributing code. Middle and last authors, meanwhile, were statistically significantly less likely to contribute code, with only `{python} percent_middle_authors_code_contributors_str` of middle authors and `{python} percent_last_authors_code_contributors_str` of last authors acting as code-contributing members of the research team. Corresponding authors were similarly less likely than expected to be code contributors, as we found that within our dataset, corresponding authors were code contributors `{python} percent_corresponding_authors_code_contributors_str` of the time. These patterns align with traditional scientific labor distribution where first authors might be expected to handle technical aspects of research while middle and last authors are likely specialist contributors or provide guidance and oversight [@Larivire2020InvestigatingTD; @sauermann2017authorship]. However, our data did not support our initial hypothesis that corresponding authors would also be more likely to contribute code due to their shared responsibility for the long-term maintenance of research artifacts. This finding suggests a potential strict division between project management responsibilities and direct technical engagement with software development. 

The modest citation advantage associated with code-contributing authors (\~4.2% increase in citations per code-contributing author) stands in contrast with the significant negative relationship between coding frequency and an individual's scholarly impact (h-index). This misalignment between code contributions and scientific recognition creates an asymmetrical relationship in which software development may enhance research impact but potentially penalizes individual careers. The progressive reduction in h-index as coding frequency increases indicates a cumulative disadvantage for frequent code contributors. This pattern persists even when controlling for publication count, suggesting issues in how software contributions are valued relative to other scientific outputs. These findings echo concerns raised by @muna2016astropyproblem about the sustainability of research software development and highlight how current reward structures may discourage talented developers from pursuing scientific careers.

Software development represents a form of scholarly labor that has become increasingly essential to modern research yet remains incompletely integrated into formal recognition systems. Similar to the high proportion of articles with authors who made data curation contributions towards research observed by @Larivire2020InvestigatingTD, our finding that more than a quarter of papers have unacknowledged code contributors highlights a labor role that is simultaneously common and undervalued. The prevalence of code contributions across domains demonstrates the importance of this work to contemporary research. However, the persistent exclusion of contributors from authorship suggests that researchers continue to classify software development as technical support rather than intellectual contribution. This classification may reflect disciplinary traditions that privilege certain forms of scholarly production despite the growing recognition that software represents a legitimate research output [@Katz2020RecognizingTV]. The tension between software's importance and contributors' recognition status raises questions about how we define, value, and reward different forms of scientific labor in an increasingly computational research landscape.

## Limitations

Our data collection approach introduces several methodological constraints to consider when interpreting these results. By focusing exclusively on GitHub repositories, we likely miss contributions stored on alternative platforms such as GitLab, Bitbucket, or institutional repositories, potentially skewing our understanding of contribution patterns. As @trujillo2022penumbra, @Cao2023TheRO, and @escamilla2022riseofgithub have all noted, while GitHub is the predominate host of scientific software, significant portions of research code exist on other platforms. Additionally, our reliance on public repositories means we cannot account for private repositories or code that were never publicly shared, potentially underrepresenting sensitive research areas or proprietary methods.

Further, while our data processing workflow began with ~60,000 possible article-repository pairs from PLOS, ~3,000 from JOSS, ~700 from SoftwareX, and ~180,000 from Papers with Code for a possible total of ~243,700[^12], `rs-graph-v1` contained a total of `{python} print_ready_m2m_doc_repo_links_count` article-repository pairs. Many of the possible article-repository pairs were filtered out due to the linked repository not being accessible, or the bibliometric metadata not being available. 

[^12]: Article-repository pair counts are approximate because there are no snapshots of these databases at a single point in time. The estimates are based on counts from each data source taken in October 2025.

Our labeling of article types (software article, research article, preprint) was based on the data source (PLOS, JOSS, SoftwareX, Papers with Code) and in the case of Papers with Code articles, our DOI resolution process and the document type available from OpenAlex. This approach may misclassify certain articles, especially those from Papers with Code (arXiv). One potential alternative approach would involve classification of the repository itself following the recommendations of @researchsoftwareclassifications in breaking down repositories by their role in research (e.g., "Modeling, Simulation, and Data Analysis", "Technology Research Software", and "Research Infrastructure Software"). This classification would allow us to investigate not only the differences of "software papers" vs "research articles" and "preprints" (which we believe would both typically be paired with "Modeling, Simulation, and Data Analysis" repositories), but the _purpose_ of the code as it relates to the research. However, there is currently no established automated method for performing this classification at scale.

Similarly, our simplification of author positions, domains, and article types to each author's "most common" (most frequent, with ties broken by most recent) introduces potential biases [@li2025determination]. This reduction may obscure the diversity of an author's contributions across different contexts, particularly for interdisciplinary researchers or those with varied roles in different projects. Further, these labels are created from metadata for articles only within our dataset. That is, even though a researcher may have dozens of articles, their "most common" author position, domain, and article type was determined with data for article-repository pairs. This inherently biases the dataset towards research teams who, as a collective, frequently create and share software and code as a part of their research process. While this approach was necessary for managing the complexity of our analysis, it may not fully capture the nuances of individual research careers.

Our predictive modeling approach for matching authors with developer accounts presents additional limitations. The model's performance can be affected by shorter names where less textual information is available for matching, potentially creating biases against researchers from cultures with shorter naming conventions. Organization accounts used for project management pose particular challenges for accurate matching, and while we implemented filtering mechanisms to minimize their impact, some misclassifications may persist. Furthermore, our approach may not capture all code contributors if multiple individuals developed code but only one uploaded it to a repository—creating attribution artifacts that may systematically underrepresent specific contributors, particularly junior researchers or staff who may not have direct repository access. As reported in Table S3 of the Supplementary Material, our dataset is relatively diverse, with the median preprint-repository pair having a commit duration (the number of days between the repository's creation and the repository's most recent commit) of 53 days, research article-repository pairs having a median commit duration of 114 days, and software article-repository pairs having a median commit duration of 282 days. This diversity in commit durations suggests that our dataset contains a range of development practices, including some "code dumps," as well as year, and multi-year long projects.

Our analytical approach required substantial data filtering to ensure reliable results, introducing potential selection biases in our sample. By focusing on article-repository pairs with commit activity no later than 90 days past the date of article publication and at least three authors and less than `{python} int(n_authors_97th_percentile)` authors, we may have systematically excluded certain types of research projects, particularly those with extended development timelines or extensive collaborations. Our categorization of coding status (non-coder, any coding, majority coding, always coding) necessarily simplifies complex contribution patterns. It does not account for code contributions' quality, complexity, or significance. Additionally, our reliance on OpenAlex metadata introduces certain limitations to our analysis. While OpenAlex provides good overall coverage, it lags behind proprietary databases in indexing references and citations. The lag in OpenAlex data may affect our citation-based analyses and the completeness of author metadata used in our study [@alperin2024analysis].

## Future Work

Future technical improvements may enhance our understanding of the relationship between software development and scientific recognition systems. Expanding analysis beyond GitHub to include other code hosting platforms would provide a more comprehensive understanding of scientific software development practices across domains and institutional contexts. More sophisticated entity-matching techniques could improve author-developer account identification, particularly for cases with limited information or common names. Developing more nuanced measures and classifications of code contribution type, quality, and significance beyond binary contribution identification would better capture the true impact of technical contributions to research, including extensions of the analyses documented in Table S1 and Table S2 of the Supplementary Material. These methodological advances would enable more precise tracking of how code contributions translate—or fail to translate—into formal scientific recognition, providing clearer evidence for policy interventions.

Our findings point to several directions for future research on the changing nature of scientific labor and recognition. Longitudinal studies tracking how code contribution patterns affect career trajectories would provide valuable insights into the long-term impacts of the observed h-index disparities and whether these effects vary across career stages. Comparative analyses across different scientific domains could reveal discipline-specific norms and practices around software recognition, potentially identifying models that more equitably credit technical contributions. Qualitative studies examining how research teams make authorship decisions regarding code contributors would complement our quantitative findings by illuminating the social and organizational factors influencing recognition practices. Additionally, to better understand corresponding authors' role in maintaining research artifacts, future work could remove the 90-day post-publication commit activity filter to examine long-term sustainability actions. However, this approach must address introducing contributors unrelated to the original paper.

Despite their growing importance, the persistent under-recognition of software contributions suggests a need for structural interventions in how we conceptualize and reward scientific work. Building upon efforts like CRediT [@brand2015beyond], future work should investigate potential policy changes to better align institutional incentives with the diverse spectrum of contributions that drive modern scientific progress. However, as the example of CRediT demonstrates, even well-intentioned taxonomies may reproduce existing hierarchies or create new forms of inequality if they fail to address underlying power dynamics in scientific communities. The challenge is not merely technical but social: creating recognition systems that simultaneously support innovation, ensure appropriate credit, maintain research integrity, and foster equitable participation in an increasingly computational scientific enterprise.

# Acknowledgments {-}

We thank our anonymous reviewers for their helpful feedback. We especially thank Molly Blank, Shahan Ali Memnon, David Farr, and Jevin West for their valuable insights at multiple stages of this research.

# Author Contributions {-}

Eva Maxfield Brown: Conceptualization, Data Curation, Formal Analysis, Investigation, Methodology, Software, Validation, Visualization, Writing - original draft, Writing - review & editing.

Isaac Slaughter: Formal Analysis, Visualization, Writing - review & editing.

Nicholas Weber: Conceptualization, Data Curation, Formal Analysis, Funding Acquisition, Investigation, Methodology, Project Administration, Resources, Supervision, Writing - original draft, Writing - review & editing.

# Competing Interests {-}

The authors have no competing interests.

# Funding Information {-}

This research was supported by grants from the National Science Foundation's (NSF) Office of Advanced Cyberinfrastructure (OAC-2211275) and the Sloan Foundation (G-2022-19347).

# Data Availability {-}

The software and code used to train, evaluate, and apply the author-developer account matching model is available at: <https://github.com/evamaxfield/sci-soft-models> (<https://doi.org/10.5281/zenodo.17401863>). The software and code used to gather, process, and analyze the dataset of linked scientific articles and code repositories and their associated contributors and metadata is available at: <https://github.com/evamaxfield/rs-graph> (<https://doi.org/10.5281/zenodo.17401960>). The compiled rs-graph-v1 dataset, as well as data required for model training and evaluation, is available at: <https://doi.org/10.7910/DVN/KPYVI1>. Certain portions of the compiled rs-graph-v1 dataset, and the model training and evaluation datasets contain linked personal data (e.g., author names, developer account usernames) and are only available by request.

# References {-}

::: {#refs}
:::
