name: Data Processing

on: 
  workflow_dispatch:
    inputs:
      dataset-source:
        description: "Which dataset to process"
        required: true
        type: string

# adding permissions to tackle error: 'Resource not accessible by integration'
permissions:
  actions: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: iterative/setup-cml@v2
        with:
          vega: false
      - name: Deploy Runner
        env:
            REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          cml runner \
              --single \
              --cloud=gcp \
              --cloud-region=us-central1-a \
              --cloud-type=e2-standard-8 \
              --labels=cml-runner

  run-command:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container: python:3.11
    timeout-minutes: 14400 # 1 week
    steps:
      - uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel uv
          uv pip install "."

      - name: Run Command
        env:
            GITHUB_TOKENS: ${{ secrets.ALL_GITHUB_TOKENS_FOR_API }}
        run: |
            rs-graph-pipelines \
                prelinked-dataset-ingestion \
                ${{ github.event.inputs.dataset-source }} \
                --use-dask \
                --prod